/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.paneles;

import util.JavaUtil;
import hibernate.DAO.ObjectModelDAO;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelos.mapeos.Almacen;
import modelos.mapeos.Contacto;
import modelos.mapeos.Ubicacion;

/**
 *
 * @author Usuario
 */
public class JPalmacen extends javax.swing.JPanel {

    private int pos;
    private List resultListAlmacen;
    private List resultListUbicacion;
    private List resultListContacto;
    private String rutaLogoModif;
    private String rutaLogoCrear;
    private final String nomeclatura = "almacen_";
    private final String extencionImg = "jpg";

    public JPalmacen() {
        initComponents();
        
         tablaModfAlmacen.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent lse) {
                if (!lse.getValueIsAdjusting()) {

                    pos = tablaModfAlmacen.getSelectedRow();
                    if (pos == -1) {
                        return;
                    }
                    Almacen a = (Almacen) resultListAlmacen.get(pos);
                    lb_id.setText(a.getIdAlmacen().toString());
                    if (a.getIdContactoGerente() != null) {
                        cb_contacto1.setSelectedItem(a.getIdContactoGerente().getNombre() + " "
                                + a.getIdContactoGerente().getPuesto() + " " + a.getIdContactoGerente().getTelefono1());
                    } else {
                        cb_contacto1.setSelectedIndex(-1);
                    }
                    if (a.getIdUbicacion() != null) {
                        cb_ubicacion1.setSelectedItem(a.getIdUbicacion().toString());
                    } else {
                        cb_ubicacion1.setSelectedIndex(-1);
                    }
                    fieldNomb1.setText(a.getNombre());
                    fieldDescripcion1.setText(a.getDescripcion());
                    fieldTlf3.setText(a.getTelefono1());
                    fieldTlf4.setText(a.getTelefono2());
                    fieldFax1.setText(a.getFax());
                    fieldCodPostal1.setText(a.getCodPostal());
                    fieldRif1.setText(a.getRif());
                    fieldEmail1.setText(a.getEmail());
                    rutaLogoModif = "";
                    String ruta = a.getLogo();
                    JavaUtil.preCambio(ruta, fieldLogo1);
                }
            }
        });

        listadoAlmacenes.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent lse) {
                if (!lse.getValueIsAdjusting()) {
                    if (listadoAlmacenes.getSelectedRow() == -1) {
                        return;
                    }
                    String ruta = ((Almacen) resultListAlmacen.get(listadoAlmacenes.getSelectedRow())).getLogo();
                    JavaUtil.preCambio(ruta, logo);
                }
            }
        });

        tablaDeletAlmacen.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent lse) {
                if (!lse.getValueIsAdjusting()) {

                    if (tablaDeletAlmacen.getSelectedRow() == -1) {
                        return;
                    }
                    pos = tablaDeletAlmacen.getSelectedRow();
                    String ruta = ((Almacen) resultListAlmacen.get(pos)).getLogo();
                    JavaUtil.preCambio(ruta, fieldLogo2);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filesc = new javax.swing.JFileChooser();
        filesc.setCurrentDirectory(new java.io.File("C:\\Users\\Usuario\\Documents\\PASANTIA"));

        filesc.setDialogTitle("Seleccione un archivo");
        panelScrudContact = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listadoAlmacenes = new org.jdesktop.swingx.JXTable();
        logo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bCrearAlmacen = new javax.swing.JButton();
        fieldNomb = new javax.swing.JTextField();
        fieldDescripcion = new javax.swing.JTextField();
        fieldTlf1 = new javax.swing.JTextField();
        fieldTlf2 = new javax.swing.JTextField();
        fieldEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        fieldFax = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        fieldCodPostal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        fieldRif = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cb_ubicacion = new javax.swing.JComboBox();
        cb_contacto = new javax.swing.JComboBox();
        addUbicacion = new javax.swing.JButton();
        addContacto = new javax.swing.JButton();
        fieldLogo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lb_id = new javax.swing.JLabel();
        bModfAlmacen = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaModfAlmacen = new org.jdesktop.swingx.JXTable();
        fieldDescripcion1 = new javax.swing.JTextField();
        fieldTlf3 = new javax.swing.JTextField();
        fieldTlf4 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        fieldNomb1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        fieldEmail1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        fieldFax1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fieldCodPostal1 = new javax.swing.JTextField();
        fieldRif1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cb_ubicacion1 = new javax.swing.JComboBox();
        cb_contacto1 = new javax.swing.JComboBox();
        addUbicacion1 = new javax.swing.JButton();
        addContacto1 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        fieldLogo1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        bDeletAlmacen = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaDeletAlmacen = new org.jdesktop.swingx.JXTable();
        fieldLogo2 = new javax.swing.JLabel();

        filesc.setCurrentDirectory(new java.io.File("\\\\SERVIDOR\\datos_usuarios en D\\PASANTIA2014\\Logos"));

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        panelScrudContact.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                panelScrudContactStateChanged(evt);
            }
        });

        listadoAlmacenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Descripción", "Tlf 1.", "Tlf 2.", "Fax", "Cod. Postal", "Email", "Ubicación", "Contacto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listadoAlmacenes.setHorizontalScrollEnabled(true);
        jScrollPane2.setViewportView(listadoAlmacenes);

        logo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
            .addComponent(logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelScrudContact.addTab("Consultar", jPanel1);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Descripción:");

        jLabel3.setText("Teléfono 1:");

        jLabel4.setText("Telefono 2:");

        jLabel5.setText("Email:");

        bCrearAlmacen.setText("Crear Almacen");
        bCrearAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearAlmacenActionPerformed(evt);
            }
        });

        jLabel12.setText("Fax:");

        jLabel13.setText("Código Postal:");

        jLabel14.setText("Rif:");

        jLabel15.setText("Ubicación:");

        jLabel16.setText("Contacto:");

        jLabel17.setText("Logo:");

        addUbicacion.setText("+");

        addContacto.setText("+");
        addContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addContactoActionPerformed(evt);
            }
        });

        fieldLogo.setToolTipText("Doble Click");
        fieldLogo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fieldLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldLogoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(addUbicacion)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addGap(68, 68, 68)
                            .addComponent(fieldLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(143, 143, 143)
                            .addComponent(bCrearAlmacen)
                            .addGap(116, 116, 116))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16)
                                .addComponent(jLabel15))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cb_ubicacion, 0, 539, Short.MAX_VALUE)
                                .addComponent(cb_contacto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(7, 7, 7)
                            .addComponent(addContacto)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldTlf2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldTlf1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(fieldNomb, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fieldFax)
                                .addComponent(fieldRif)
                                .addComponent(fieldCodPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldNomb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(fieldFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(fieldCodPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldTlf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(fieldRif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fieldTlf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUbicacion)
                    .addComponent(jLabel15))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addContacto)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(fieldLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 70, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(54, 54, 54))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(bCrearAlmacen)
                                .addGap(67, 67, 67))))))
        );

        panelScrudContact.addTab("Crear", jPanel2);

        jLabel6.setText("ID:");

        lb_id.setText("id contacto");

        bModfAlmacen.setText("Modificar");
        bModfAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModfAlmacenActionPerformed(evt);
            }
        });

        tablaModfAlmacen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Descripción", "Tlf 1.", "Tlf 2.", "Fax", "Cod. Postal", "Email", "Ubicación", "Contacto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaModfAlmacen.setHorizontalScrollEnabled(true);
        jScrollPane5.setViewportView(tablaModfAlmacen);

        jLabel18.setText("Nombre:");

        jLabel19.setText("Descripción:");

        jLabel20.setText("Teléfono 1:");

        jLabel21.setText("Telefono 2:");

        jLabel22.setText("Código Postal:");

        jLabel23.setText("Rif:");

        jLabel24.setText("Fax:");

        jLabel7.setText("Email:");

        jLabel25.setText("Ubicación:");

        jLabel26.setText("Contacto:");

        addUbicacion1.setText("+");

        addContacto1.setText("+");

        jLabel27.setText("Logo:");

        fieldLogo1.setToolTipText("Doble Click");
        fieldLogo1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldLogo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fieldLogo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldLogo1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel7))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fieldRif1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldCodPostal1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(fieldFax1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldNomb1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldTlf4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldTlf3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(lb_id))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel27))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cb_ubicacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cb_contacto1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(addContacto1)
                                            .addComponent(addUbicacion1)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fieldLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)))))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bModfAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lb_id))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldNomb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldTlf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldTlf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldFax1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(fieldCodPostal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(fieldRif1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_ubicacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUbicacion1)
                    .addComponent(jLabel25))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_contacto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addContacto1)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(fieldLogo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bModfAlmacen)
                .addContainerGap())
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );

        panelScrudContact.addTab("Modificar", jPanel3);

        bDeletAlmacen.setText("Eliminar");
        bDeletAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeletAlmacenActionPerformed(evt);
            }
        });

        tablaDeletAlmacen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Descripción", "Tlf 1.", "Tlf 2.", "Fax", "Cod. Postal", "Email", "Ubicación", "Contacto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDeletAlmacen.setHorizontalScrollEnabled(true);
        jScrollPane6.setViewportView(tablaDeletAlmacen);

        fieldLogo2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldLogo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bDeletAlmacen, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(fieldLogo2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bDeletAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelScrudContact.addTab("Eliminar", jPanel4);

        add(panelScrudContact);
    }// </editor-fold>//GEN-END:initComponents

    private void pickImg(JLabel lbl) {

        filesc.setFileFilter(new FileNameExtensionFilter("Archivoss JPG ", extencionImg));

        int returnVal = filesc.showOpenDialog(this);
        try {
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                JavaUtil.cambiarImg(filesc.getSelectedFile(), lbl);
            } else {
                JavaUtil.cambiarImg(null, lbl);
            }
        } catch (IOException ex) {
            Logger.getLogger(JPalmacen.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    private void bCrearAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearAlmacenActionPerformed
        if (!fieldNomb.getText().equals("") && !fieldDescripcion.getText().equals("")
                && !fieldTlf1.getText().equals("") && !fieldTlf2.getText().equals("") && !fieldEmail.getText().equals("")) {

            if (JOptionPane.showConfirmDialog(this, "¿Está seguro de crear el"
                    + " nuevo Almacen con nombre : " + fieldNomb.getText() + "?",
                    "Información", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                Almacen nuevo_almacen = new Almacen(
                        fieldNomb.getText(),
                        fieldTlf1.getText(),
                        fieldTlf2.getText(),
                        fieldFax.getText(),
                        fieldCodPostal.getText(),
                        fieldEmail.getText(),
                        fieldDescripcion.getText(),
                        fieldRif.getText(),
                        "",
                        (Contacto) resultListContacto.get(cb_contacto.getSelectedIndex()),
                        (Ubicacion) resultListUbicacion.get(cb_ubicacion.getSelectedIndex())
                );
                Integer id_almacen = (Integer) ObjectModelDAO.saveObject(nuevo_almacen);
                String rutaFinal = JavaUtil.cons_rutaImgsAlmacen + nomeclatura + id_almacen + "." + extencionImg;
                try {
                    JavaUtil.copyFile(rutaLogoCrear, rutaFinal);
                } catch (IOException ex) {
                    Logger.getLogger(JPalmacen.class.getName()).log(Level.SEVERE, null, ex);
                }
                nuevo_almacen.setLogo(rutaFinal);
                ObjectModelDAO.updateObject(nuevo_almacen);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");
        }
    }//GEN-LAST:event_bCrearAlmacenActionPerformed

    private void addContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addContactoActionPerformed

    private void fieldLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldLogoMouseClicked
        if (evt.getClickCount() == 2) {
            pickImg(fieldLogo);
            if (fieldLogo.getIcon() != null) {
                rutaLogoCrear = filesc.getSelectedFile().getPath();
            }
        }
    }//GEN-LAST:event_fieldLogoMouseClicked

    private void bModfAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModfAlmacenActionPerformed
        if (pos == -1 || fieldNomb1.getText().equals("") || fieldDescripcion1.getText().equals("")
                || fieldTlf3.getText().equals("") || fieldTlf4.getText().equals("") || fieldFax1.getText().equals("")) {

            return;
        }

        String valor = tablaModfAlmacen.getValueAt(tablaModfAlmacen.getSelectedRow(), 0).toString();
        if (JOptionPane.showConfirmDialog(this, "¿Está seguro de modificar la"
                + " el contacto " + valor + "?",
                "Información", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

            try {
                int pos = this.pos;
                Almacen a = (Almacen) resultListAlmacen.get(pos);
                a.setNombre(fieldNomb1.getText());
                a.setDescripcion(fieldDescripcion1.getText());
                a.setTelefono1(fieldTlf3.getText());
                a.setTelefono2(fieldTlf4.getText());
                a.setFax(fieldFax1.getText());
                a.setCodPostal(fieldCodPostal1.getText());
                a.setRif(fieldRif1.getText());
                a.setEmail(fieldEmail1.getText());
                a.setIdUbicacion((Ubicacion) resultListUbicacion.get(cb_ubicacion1.getSelectedIndex()));
                a.setIdContactoGerente((Contacto) resultListContacto.get(cb_contacto1.getSelectedIndex()));
                JavaUtil.copyFile(rutaLogoModif, a.getLogo());
                a.setLogo(rutaLogoModif);
                ObjectModelDAO.updateObject(a);

                String sql = "FROM Almacen a order by a.idAlmacen asc";
                resultListAlmacen = ObjectModelDAO.getResultQuery(sql);
                JavaUtil.displayResult(resultListAlmacen, tablaModfAlmacen);
                tablaModfAlmacen.setEditable(false);
                tablaModfAlmacen.setRowSelectionInterval(pos, pos);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(
                        null,
                        "Mensaje:\n\t" + e.getMessage(),
                        "Error Update",
                        JOptionPane.ERROR_MESSAGE
                );
                Logger.getLogger(JPalmacen.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_bModfAlmacenActionPerformed

    private void fieldLogo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldLogo1MouseClicked
        if (evt.getClickCount() == 2) {
            pickImg(fieldLogo1);
            if (fieldLogo1.getIcon() != null) {
                rutaLogoModif = filesc.getSelectedFile().getPath();
            }
        }
    }//GEN-LAST:event_fieldLogo1MouseClicked

    private void bDeletAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeletAlmacenActionPerformed
        if (pos == -1) {
            return;
        }

        String valor = tablaDeletAlmacen.getValueAt(tablaDeletAlmacen.
                getSelectedRow(), tablaDeletAlmacen.getSelectedColumn()).toString();
        if (JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar el "
                + " Contacto " + tablaDeletAlmacen.getValueAt(tablaDeletAlmacen.getSelectedRow(), 1)
                + "?", "Información", JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION) {

            Almacen a = (Almacen) resultListAlmacen.get(pos);
            File file = new File(a.getLogo());

            if (file.delete()) {
                System.out.println(file.getPath() + " is deleted!");
            } else {
                System.out.println("Delete operation is failed.");
            }

            ObjectModelDAO.deleteObject(a);
            String sql = "FROM Almacen a order by a.idAlmacen asc";
            resultListAlmacen = ObjectModelDAO.getResultQuery(sql);
            JavaUtil.displayResult(resultListAlmacen, tablaDeletAlmacen);
            pos = -1;
            tablaDeletAlmacen.setEditable(false);
            JavaUtil.preCambio(null, fieldLogo2);
        }
    }//GEN-LAST:event_bDeletAlmacenActionPerformed

    private void panelScrudContactStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_panelScrudContactStateChanged
        if (panelScrudContact.getSelectedIndex() == 0) {
            String sql = "FROM Almacen a order by a.idAlmacen asc";
            resultListAlmacen = ObjectModelDAO.getResultQuery(sql);
            JavaUtil.displayResult(resultListAlmacen, listadoAlmacenes);
            listadoAlmacenes.setEditable(false);
            JavaUtil.preCambio(null, logo);
        }

        if (panelScrudContact.getSelectedIndex() == 1) {
            fieldNomb.setText("");
            fieldDescripcion.setText("");
            fieldTlf1.setText("");
            fieldTlf2.setText("");
            fieldEmail.setText("");
            fieldFax.setText("");
            fieldCodPostal.setText("");
            fieldRif.setText("");
            JavaUtil.preCambio(null, fieldLogo);
            rutaLogoCrear = "";
            resultListUbicacion = ObjectModelDAO.getResultQuery("FROM Ubicacion u order by u.idUbicacion asc");
            resultListContacto = ObjectModelDAO.getResultQuery("FROM Contacto c order by c.idContacto asc");
            cb_ubicacion.removeAllItems();
            cb_contacto.removeAllItems();

            for (Object object : resultListUbicacion) {
                Ubicacion u = (Ubicacion) object;
                cb_ubicacion.addItem(u.toString());
            }

            for (Object object : resultListContacto) {
                Contacto c = (Contacto) object;
                cb_contacto.addItem(c.getNombre() + " " + c.getPuesto() + " " + c.getTelefono1());
            }
        }

        if (panelScrudContact.getSelectedIndex() == 2) {
            lb_id.setText("");
            fieldNomb1.setText("");
            fieldDescripcion1.setText("");
            fieldTlf3.setText("");
            fieldTlf4.setText("");
            fieldEmail1.setText("");
            fieldFax1.setText("");
            fieldCodPostal1.setText("");
            fieldRif1.setText("");
            JavaUtil.preCambio(null, fieldLogo1);
            rutaLogoModif = "";
            resultListUbicacion = ObjectModelDAO.getResultQuery("FROM Ubicacion u order by u.idUbicacion asc");
            resultListContacto = ObjectModelDAO.getResultQuery("FROM Contacto c order by c.idContacto asc");
            cb_ubicacion1.removeAllItems();
            cb_contacto1.removeAllItems();

            for (Object object : resultListUbicacion) {
                Ubicacion u = (Ubicacion) object;
                cb_ubicacion1.addItem(u.toString());
            }

            for (Object object : resultListContacto) {
                Contacto c = (Contacto) object;
                cb_contacto1.addItem(c.getNombre() + " " + c.getPuesto() + " " + c.getTelefono1());
            }
            cb_ubicacion1.setSelectedIndex(-1);
            cb_contacto1.setSelectedIndex(-1);
            String sql = "FROM Almacen a order by a.idAlmacen asc";
            resultListAlmacen = ObjectModelDAO.getResultQuery(sql);
            JavaUtil.displayResult(resultListAlmacen, tablaModfAlmacen);
            pos = -1;
            tablaModfAlmacen.setEditable(false);

        }

        if (panelScrudContact.getSelectedIndex() == 3) {
            String sql = "FROM Almacen a order by a.idAlmacen asc";
            resultListAlmacen = ObjectModelDAO.getResultQuery(sql);

            JavaUtil.displayResult(resultListAlmacen, tablaDeletAlmacen);
            pos = -1;
            tablaDeletAlmacen.setEditable(false);
            JavaUtil.preCambio(null, fieldLogo2);
        }
    }//GEN-LAST:event_panelScrudContactStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addContacto;
    private javax.swing.JButton addContacto1;
    private javax.swing.JButton addUbicacion;
    private javax.swing.JButton addUbicacion1;
    private javax.swing.JButton bCrearAlmacen;
    private javax.swing.JButton bDeletAlmacen;
    private javax.swing.JButton bModfAlmacen;
    private javax.swing.JComboBox cb_contacto;
    private javax.swing.JComboBox cb_contacto1;
    private javax.swing.JComboBox cb_ubicacion;
    private javax.swing.JComboBox cb_ubicacion1;
    private javax.swing.JTextField fieldCodPostal;
    private javax.swing.JTextField fieldCodPostal1;
    private javax.swing.JTextField fieldDescripcion;
    private javax.swing.JTextField fieldDescripcion1;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldEmail1;
    private javax.swing.JTextField fieldFax;
    private javax.swing.JTextField fieldFax1;
    private javax.swing.JLabel fieldLogo;
    private javax.swing.JLabel fieldLogo1;
    private javax.swing.JLabel fieldLogo2;
    private javax.swing.JTextField fieldNomb;
    private javax.swing.JTextField fieldNomb1;
    private javax.swing.JTextField fieldRif;
    private javax.swing.JTextField fieldRif1;
    private javax.swing.JTextField fieldTlf1;
    private javax.swing.JTextField fieldTlf2;
    private javax.swing.JTextField fieldTlf3;
    private javax.swing.JTextField fieldTlf4;
    private javax.swing.JFileChooser filesc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lb_id;
    private org.jdesktop.swingx.JXTable listadoAlmacenes;
    private javax.swing.JLabel logo;
    private javax.swing.JTabbedPane panelScrudContact;
    private org.jdesktop.swingx.JXTable tablaDeletAlmacen;
    private org.jdesktop.swingx.JXTable tablaModfAlmacen;
    // End of variables declaration//GEN-END:variables
}
