/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.paneles;

import util.JavaUtil;
import static util.JavaUtil.setTableCellAlignment;
import hibernate.DAO.ObjectModelDAO;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;
import modelos.mapeos.Contacto;
import modelos.tablas.TableModelReport;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import static org.jdesktop.swingx.JXLabel.TextAlignment.CENTER;
import org.jdesktop.swingx.JXTable;

public class JPcontacto extends javax.swing.JPanel {

    private int pos;
    private List resultListContacto;

    public final String rutaJasper = "/reportes/ReporteContactos.jasper";
    private Integer tabCrud;

    public JPcontacto() {
        this(0);
    }

    public JPcontacto(Integer tabCrud) {
        this.tabCrud = tabCrud;
        initComponents();

        setTableCellAlignment(JLabel.CENTER, listadoContactos);
        setTableCellAlignment(JLabel.CENTER, tablaModfContact);
        setTableCellAlignment(JLabel.CENTER, tablaDeletContact);
        listadoContactos.getTableHeader().setReorderingAllowed(false);
        tablaModfContact.getTableHeader().setReorderingAllowed(false);
        tablaDeletContact.getTableHeader().setReorderingAllowed(false);

        tablaModfContact.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent lse) {
                if (!lse.getValueIsAdjusting()) {

                    pos = tablaModfContact.getSelectedRow();
                    if (pos == -1) {
                        return;
                    }
                    Contacto c = (Contacto) resultListContacto.get(pos);
                    lb_id.setText(c.getIdContacto().toString());
                    fieldNombContact.setText(c.getNombre());
                    fieldPuestContact.setText(c.getPuesto());
                    fieldTlfContact1.setText(c.getTelefono1());
                    fieldTlfContact2.setText(c.getTelefono2());
                    fieldEmailContact.setText(c.getEmail());
                }
            }
        });

        tablaDeletContact.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent lse) {
                if (!lse.getValueIsAdjusting()) {

                    if (tablaDeletContact.getSelectedRow() == -1) {
                        return;
                    }
                    pos = tablaDeletContact.getSelectedRow();

                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelScrudContact = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listadoContactos = new org.jdesktop.swingx.JXTable();
        jLabel12 = new javax.swing.JLabel();
        jb_GenerarReporteContacto = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bCrearContac = new javax.swing.JButton();
        fieldNomb = new javax.swing.JTextField();
        fieldPuest = new javax.swing.JTextField();
        fieldTlf1 = new javax.swing.JTextField();
        fieldtlf2 = new javax.swing.JTextField();
        fieldEmail = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaCrearContactos = new org.jdesktop.swingx.JXTable();
        jScrollPane16 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaModfContact = new org.jdesktop.swingx.JXTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lb_id = new javax.swing.JLabel();
        fieldNombContact = new javax.swing.JTextField();
        fieldPuestContact = new javax.swing.JTextField();
        fieldTlfContact1 = new javax.swing.JTextField();
        fieldTlfContact2 = new javax.swing.JTextField();
        fieldEmailContact = new javax.swing.JTextField();
        bModfContact = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane17 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaDeletContact = new org.jdesktop.swingx.JXTable();
        bDeletContact = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(621, 467));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        panelScrudContact.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                panelScrudContactStateChanged(evt);
            }
        });

        listadoContactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Contacto", "Nombre", "Puesto", "Telefono 1", "Telefono 2", "Correo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listadoContactos.setHorizontalScrollEnabled(true);
        listadoContactos.setSortable(false);
        jScrollPane2.setViewportView(listadoContactos);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1416622346_xmag.png"))); // NOI18N
        jLabel12.setText("Para realizar Busqueda: Haga Click en la tabla + CTRL F");

        jb_GenerarReporteContacto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Reporte.png"))); // NOI18N
        jb_GenerarReporteContacto.setText("Generar Reporte");
        jb_GenerarReporteContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_GenerarReporteContactoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jb_GenerarReporteContacto)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jb_GenerarReporteContacto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        panelScrudContact.addTab("Consultar", jScrollPane1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1418698596_user-24.png"))); // NOI18N
        jLabel1.setText("Nombre:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1418698876_id-card.png"))); // NOI18N
        jLabel2.setText("Puesto:");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/telefono.png"))); // NOI18N
        jLabel3.setText("Telefono 1:");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/telefono.png"))); // NOI18N
        jLabel4.setText("Telefono 2:");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/correo.png"))); // NOI18N
        jLabel5.setText("Correo:");

        bCrearContac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1415663093_add-user.png"))); // NOI18N
        bCrearContac.setText("Crear Contacto");
        bCrearContac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearContacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(183, 183, 183))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addGap(168, 168, 168)))
                    .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldtlf2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNomb, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPuest, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldTlf1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCrearContac)
                    .addComponent(jLabel2)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(fieldNomb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldPuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(fieldTlf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(fieldtlf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(bCrearContac)
                .addGap(65, 65, 65))
        );

        jPanel2.add(jPanel5, java.awt.BorderLayout.WEST);

        tablaCrearContactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID CONTACTO", "NOMBRE", "PUESTO", "TELEFONO 1", "TELEFONO 2", "CORREO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tablaCrearContactos);

        jPanel2.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        jScrollPane5.setViewportView(jPanel2);

        panelScrudContact.addTab("Crear", jScrollPane5);

        jPanel3.setPreferredSize(new java.awt.Dimension(5, 352));
        jPanel3.setLayout(new java.awt.BorderLayout());

        tablaModfContact.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Puesto", "Telefono 1", "Telefono 2", "Correo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaModfContact.setHorizontalScrollEnabled(true);
        tablaModfContact.setSortable(false);
        jScrollPane4.setViewportView(tablaModfContact);

        jPanel3.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jLabel6.setText("ID:");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1418698596_user-24.png"))); // NOI18N
        jLabel7.setText("Nombre Contacto:");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1418698876_id-card.png"))); // NOI18N
        jLabel8.setText("Puesto del Conctacto:");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/telefono.png"))); // NOI18N
        jLabel9.setText("Telefono 1 :");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/telefono.png"))); // NOI18N
        jLabel10.setText("Telefono 2:");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/correo.png"))); // NOI18N
        jLabel11.setText("Correo:");

        lb_id.setText("id contacto");

        bModfContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1415663100_edit-user.png"))); // NOI18N
        bModfContact.setText("Modificar");
        bModfContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModfContactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_id))
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(fieldNombContact, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(fieldPuestContact)
                    .addComponent(fieldTlfContact1)
                    .addComponent(fieldTlfContact2)
                    .addComponent(fieldEmailContact))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(bModfContact)
                .addGap(23, 23, 23))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lb_id))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldNombContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldPuestContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldTlfContact1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldTlfContact2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldEmailContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bModfContact, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel6, java.awt.BorderLayout.EAST);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1416622346_xmag.png"))); // NOI18N
        jLabel13.setText("Para realizar Busqueda: Haga Click en la tabla + CTRL F");
        jPanel3.add(jLabel13, java.awt.BorderLayout.PAGE_START);

        jScrollPane16.setViewportView(jPanel3);

        panelScrudContact.addTab("Modificar", jScrollPane16);

        jPanel4.setPreferredSize(new java.awt.Dimension(5, 5));

        tablaDeletContact.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Puesto", "Telefono 1", "Telefono 2", "Correo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDeletContact.setHorizontalScrollEnabled(true);
        tablaDeletContact.setSortable(false);
        jScrollPane3.setViewportView(tablaDeletContact);

        bDeletContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1415663088_delete-user.png"))); // NOI18N
        bDeletContact.setText("Eliminar");
        bDeletContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeletContactActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1416622346_xmag.png"))); // NOI18N
        jLabel14.setText("Para realizar Busqueda: Haga Click en la tabla + CTRL F");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bDeletContact)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(bDeletContact, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jScrollPane17.setViewportView(jPanel4);

        panelScrudContact.addTab("Eliminar", jScrollPane17);

        add(panelScrudContact);
    }// </editor-fold>//GEN-END:initComponents

    private void bCrearContacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearContacActionPerformed
        if (!fieldNomb.getText().equals("") && !fieldPuest.getText().equals("")
                && !fieldTlf1.getText().equals("") && !fieldtlf2.getText().equals("") && !fieldEmail.getText().equals("")) {
            if (JOptionPane.showConfirmDialog(this, "¿Está seguro de crear el"
                    + " nuevo contacto con nombre : " + fieldNomb.getText() + "?",
                    "Información", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                ObjectModelDAO.saveObject(new Contacto(fieldNomb.getText(), fieldPuest.getText(), fieldTlf1.getText(),
                        fieldtlf2.getText(), fieldEmail.getText()));
                
                String sql = "FROM Contacto c order by c.idContacto asc";
                resultListContacto = ObjectModelDAO.getResultQuery(sql);
                JavaUtil.displayResult(resultListContacto, tablaCrearContactos);
                tablaCrearContactos.setEditable(false);
                tablaCrearContactos.setRowSelectionInterval(resultListContacto.size()-1, resultListContacto.size()-1);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");
        }
    }//GEN-LAST:event_bCrearContacActionPerformed

    private void bModfContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModfContactActionPerformed
        if (pos == -1 || fieldNombContact.getText().equals("") || fieldPuestContact.getText().equals("")
                || fieldTlfContact1.getText().equals("") || fieldTlfContact2.getText().equals("") || fieldEmailContact.getText().equals("")) {

            return;
        }

        String valor = tablaModfContact.getValueAt(tablaModfContact.getSelectedRow(), 0).toString();
        if (JOptionPane.showConfirmDialog(this, "¿Está seguro de modificar la"
                + " el contacto " + valor + "?",
                "Información", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

            try {
                int pos = this.pos;
                Contacto c = (Contacto) resultListContacto.get(pos);
                c.setNombre(fieldNombContact.getText());
                c.setPuesto(fieldPuestContact.getText());
                c.setTelefono1(fieldTlfContact1.getText());
                c.setTelefono2(fieldTlfContact2.getText());
                c.setEmail(fieldEmail.getText());
                ObjectModelDAO.updateObject(c);

                String sql = "FROM Contacto c order by c.idContacto asc";
                resultListContacto = ObjectModelDAO.getResultQuery(sql);
                JavaUtil.displayResult(resultListContacto, tablaModfContact);
                tablaModfContact.setEditable(false);
                tablaModfContact.setRowSelectionInterval(pos, pos);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(
                        null,
                        "Mensaje:\n\t" + e.getMessage(),
                        "Error Update",
                        JOptionPane.ERROR_MESSAGE
                );
                Logger.getLogger(JPcontacto.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_bModfContactActionPerformed

    private void bDeletContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeletContactActionPerformed
        if (pos == -1) {
            return;
        }

        String valor = tablaDeletContact.getValueAt(tablaDeletContact.
                getSelectedRow(), tablaDeletContact.getSelectedColumn()).toString();
        if (JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar el "
                + " Contacto " + tablaDeletContact.getValueAt(tablaDeletContact.getSelectedRow(), 1)
                + "?", "Información", JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION) {

            ObjectModelDAO.deleteObject(resultListContacto.get(pos));
            String sql = "FROM Contacto c order by c.idContacto asc";
            resultListContacto = ObjectModelDAO.getResultQuery(sql);
            JavaUtil.displayResult(resultListContacto, tablaDeletContact);
            pos = -1;
            tablaDeletContact.setEditable(false);
        }
    }//GEN-LAST:event_bDeletContactActionPerformed

    private void panelScrudContactStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_panelScrudContactStateChanged

        if (panelScrudContact.getTabCount() != 4) {
            return;
        }

        //verifica si debe abrir un panel desde la llamada
        if (this.tabCrud != null) {
            int tabCrud = this.tabCrud.intValue();
            this.tabCrud = null;
            panelScrudContact.setSelectedIndex(tabCrud);
            return;
        }

        if (panelScrudContact.getSelectedIndex() == 0) {
            String sql = "FROM Contacto c order by c.idContacto asc";
            List resultList = ObjectModelDAO.getResultQuery(sql);
            JavaUtil.displayResult(resultList, listadoContactos);
            listadoContactos.setEditable(false);
        }

        if (panelScrudContact.getSelectedIndex() == 1) {
            fieldNomb.setText("");
            fieldPuest.setText("");
            fieldTlf1.setText("");
            fieldtlf2.setText("");
            fieldEmail.setText("");
            String sql = "FROM Contacto c order by c.idContacto asc";
            List resultList = ObjectModelDAO.getResultQuery(sql);
            JavaUtil.displayResult(resultList, tablaCrearContactos);
            tablaCrearContactos.setEditable(false);
        }

        if (panelScrudContact.getSelectedIndex() == 2) {
            lb_id.setText("");
            fieldNombContact.setText("");
            fieldPuestContact.setText("");
            fieldTlfContact1.setText("");
            fieldTlfContact2.setText("");
            fieldEmailContact.setText("");
            String sql = "FROM Contacto c order by c.idContacto asc";
            resultListContacto = ObjectModelDAO.getResultQuery(sql);
            JavaUtil.displayResult(resultListContacto, tablaModfContact);
            pos = -1;
            tablaModfContact.setEditable(false);

        }

        if (panelScrudContact.getSelectedIndex() == 3) {
            String sql = "FROM Contacto c order by c.idContacto asc";
            resultListContacto = ObjectModelDAO.getResultQuery(sql);

            JavaUtil.displayResult(resultListContacto, tablaDeletContact);
            pos = -1;
            tablaDeletContact.setEditable(false);
        }
    }//GEN-LAST:event_panelScrudContactStateChanged

    private void generarReporte() {
        try {
            JasperPrint jasperPrint = null;
            Map<String, Object> parametro = new HashMap<>();

            TableModelReport dataSourse = new TableModelReport(listadoContactos.getModel());

            parametro.put("REPORT_DATA_SOURSE", dataSourse);
            JasperReport reporte = (JasperReport) JRLoader.loadObject(this.getClass().getResourceAsStream(rutaJasper));
            jasperPrint = JasperFillManager.fillReport(reporte, null, dataSourse);
            JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);
            jasperViewer.setTitle("Reporte de Clasificación de Producto");
            jasperViewer.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error" + e);
        }
    }

    private void jb_GenerarReporteContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_GenerarReporteContactoActionPerformed
        generarReporte();
    }//GEN-LAST:event_jb_GenerarReporteContactoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCrearContac;
    private javax.swing.JButton bDeletContact;
    private javax.swing.JButton bModfContact;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldEmailContact;
    private javax.swing.JTextField fieldNomb;
    private javax.swing.JTextField fieldNombContact;
    private javax.swing.JTextField fieldPuest;
    private javax.swing.JTextField fieldPuestContact;
    private javax.swing.JTextField fieldTlf1;
    private javax.swing.JTextField fieldTlfContact1;
    private javax.swing.JTextField fieldTlfContact2;
    private javax.swing.JTextField fieldtlf2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton jb_GenerarReporteContacto;
    private javax.swing.JLabel lb_id;
    private org.jdesktop.swingx.JXTable listadoContactos;
    private javax.swing.JTabbedPane panelScrudContact;
    private org.jdesktop.swingx.JXTable tablaCrearContactos;
    private org.jdesktop.swingx.JXTable tablaDeletContact;
    private org.jdesktop.swingx.JXTable tablaModfContact;
    // End of variables declaration//GEN-END:variables

}
