/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.paneles;

import util.JavaUtil;
import static util.JavaUtil.createJDialogGeneric;
import static util.JavaUtil.setTableCellAlignment;
import hibernate.DAO.ObjectModelDAO;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import modelos.mapeos.Departamento;
import modelos.mapeos.Division;
import modelos.tablas.TableModelReport;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

public class JPdepartamento extends javax.swing.JPanel {

    private List resultList_departamento;
    private List resultList_division;
    private int pos;
    public final String rutaJasper = "/reportes/ReporteDepartamento.jasper";
    private Integer tabCrud;

    public JPdepartamento() {
        this(0);
    }

    public JPdepartamento(Integer tabCrud) {
        this.tabCrud = tabCrud;
        initComponents();

        setTableCellAlignment(JLabel.CENTER, listadoDepartamentos);
        setTableCellAlignment(JLabel.CENTER, tablaModfDep);
        setTableCellAlignment(JLabel.CENTER, tablaDeletDep);
        listadoDepartamentos.getTableHeader().setReorderingAllowed(false);
        tablaModfDep.getTableHeader().setReorderingAllowed(false);
        tablaDeletDep.getTableHeader().setReorderingAllowed(false);

        tablaDeletDep.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent lse) {
                if (!lse.getValueIsAdjusting()) {

                    if (tablaDeletDep.getSelectedRow() == -1) {
                        return;
                    }
                    pos = tablaDeletDep.getSelectedRow();

                }
            }
        });

        tablaModfDep.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent lse) {
                if (!lse.getValueIsAdjusting()) {

                    if (tablaModfDep.getSelectedRow() == -1) {
                        return;
                    }
                    pos = tablaModfDep.getSelectedRow();
                    Departamento d = (Departamento) resultList_departamento.get(pos);
                    idDepartamento.setText(d.getIdDepartamento().toString());
                    modfNombre.setText(d.getNombre());
                    cb_divisionModificar.setSelectedItem(d.getIdDivision().getNombre());
                }
            }
        ;
    }

    );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelScrudDep = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listadoDepartamentos = new org.jdesktop.swingx.JXTable();
        jLabel14 = new javax.swing.JLabel();
        bt_GenerarReporte = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tablaCrearDepartamento = new org.jdesktop.swingx.JXTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nuevDep = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cb_divisionCrear = new javax.swing.JComboBox();
        bCrearDivision = new javax.swing.JButton();
        bCrear = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaModfDep = new org.jdesktop.swingx.JXTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        idDepartamento = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        modfNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cb_divisionModificar = new javax.swing.JComboBox();
        bCrearDivision1 = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDeletDep = new org.jdesktop.swingx.JXTable();
        bDelet_dep = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        panelScrudDep.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                panelScrudDepStateChanged(evt);
            }
        });

        listadoDepartamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID DEPARTAMENTO", "NOMBRE DEPARTAMENTO", "DIVISION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listadoDepartamentos.setSortable(false);
        jScrollPane1.setViewportView(listadoDepartamentos);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1416622346_xmag.png"))); // NOI18N
        jLabel14.setText("Para realizar Busqueda: Haga Click en la tabla + CTRL F");

        bt_GenerarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Reporte.png"))); // NOI18N
        bt_GenerarReporte.setText("Generar Reporte");
        bt_GenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_GenerarReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(40, 40, 40)
                .addComponent(bt_GenerarReporte)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(bt_GenerarReporte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jPanel1);

        panelScrudDep.addTab("Consultar", jScrollPane4);

        jPanel2.setLayout(new java.awt.BorderLayout());

        tablaCrearDepartamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID DEPARTAMENTO", "NOMBRE DEPARTAMENTO", "DIVISION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(tablaCrearDepartamento);

        jPanel2.add(jScrollPane8, java.awt.BorderLayout.CENTER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/departamento.png"))); // NOI18N
        jLabel1.setText("Nombre del Departamento");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/division.png"))); // NOI18N
        jLabel2.setText("Nombre de division");

        bCrearDivision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1415656550_Add.png"))); // NOI18N
        bCrearDivision.setText("Crear División");
        bCrearDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearDivisionActionPerformed(evt);
            }
        });

        bCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1415656550_Add.png"))); // NOI18N
        bCrear.setText("Crear Departamento");
        bCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_divisionCrear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nuevDep))
                    .addComponent(bCrearDivision))
                .addGap(25, 25, 25))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addComponent(nuevDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(21, 21, 21)
                .addComponent(cb_divisionCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(bCrearDivision)
                .addGap(34, 34, 34)
                .addComponent(bCrear)
                .addContainerGap(509, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, java.awt.BorderLayout.WEST);

        jScrollPane5.setViewportView(jPanel2);

        panelScrudDep.addTab("Crear", jScrollPane5);

        jPanel3.setLayout(new java.awt.BorderLayout());

        tablaModfDep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID DEPARTAMENTO", "NOMBRE DEPARTAMENTO", "DIVISION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaModfDep.setHorizontalScrollEnabled(true);
        tablaModfDep.setSortable(false);
        jScrollPane3.setViewportView(tablaModfDep);

        jPanel3.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jLabel6.setText("ID Departamento");

        idDepartamento.setText("ID Departamento");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/departamento.png"))); // NOI18N
        jLabel3.setText("Nombre Departamento");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/division.png"))); // NOI18N
        jLabel4.setText("Division a la que Pertenece");

        bCrearDivision1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1415656550_Add.png"))); // NOI18N
        bCrearDivision1.setText("Crear División");
        bCrearDivision1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearDivision1ActionPerformed(evt);
            }
        });

        bModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1415656862_Circulation.png"))); // NOI18N
        bModificar.setText("Modificar Departamento");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(bCrearDivision1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bModificar))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(modfNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idDepartamento))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_divisionModificar, javax.swing.GroupLayout.Alignment.LEADING, 0, 166, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(idDepartamento))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_divisionModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bCrearDivision1)
                .addGap(29, 29, 29)
                .addComponent(bModificar)
                .addContainerGap(538, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, java.awt.BorderLayout.EAST);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1416622346_xmag.png"))); // NOI18N
        jLabel15.setText("Para realizar Busqueda: Haga Click en la tabla + CTRL F");
        jPanel3.add(jLabel15, java.awt.BorderLayout.PAGE_START);

        jScrollPane6.setViewportView(jPanel3);

        panelScrudDep.addTab("Modificar", jScrollPane6);

        tablaDeletDep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID DEPARTAMENTO", "NOMBRE DEPARTAMENTO", "DIVISION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDeletDep.setHorizontalScrollEnabled(true);
        tablaDeletDep.setSortable(false);
        jScrollPane2.setViewportView(tablaDeletDep);

        bDelet_dep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1415657185_remove-sign-32.png"))); // NOI18N
        bDelet_dep.setText("Eliminar");
        bDelet_dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDelet_depActionPerformed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1416622346_xmag.png"))); // NOI18N
        jLabel16.setText("Para realizar Busqueda: Haga Click en la tabla + CTRL F");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bDelet_dep)
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(bDelet_dep, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jScrollPane7.setViewportView(jPanel4);

        panelScrudDep.addTab("Eliminar", jScrollPane7);

        panelScrudDep.setSelectedIndex(-1);

        add(panelScrudDep);
    }// </editor-fold>//GEN-END:initComponents

    private void bCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearActionPerformed
        if (!nuevDep.getText().equals("")) {
            if (JOptionPane.showConfirmDialog(this, "¿Está seguro de crear "
                    + " un nuevo departamento : " + nuevDep.getText() + "?",
                    "Información", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                ObjectModelDAO.saveObject(new Departamento(
                        nuevDep.getText(),
                        (Division) resultList_division.get(cb_divisionCrear.getSelectedIndex()))
                );

                String sql = "FROM Departamento d order by d.idDepartamento asc";
                resultList_departamento = ObjectModelDAO.getResultQuery(sql);
                JavaUtil.displayResult(resultList_departamento, tablaCrearDepartamento);
                tablaCrearDepartamento.setEditable(false);
                tablaCrearDepartamento.setRowSelectionInterval(resultList_departamento.size()-1, resultList_departamento.size()-1);
            }
        }
    }//GEN-LAST:event_bCrearActionPerformed

    private void bCrearDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearDivisionActionPerformed
        createJDialogGeneric(new JPdivision(1));
        resultList_division = ObjectModelDAO.getResultQuery("FROM Division d order by d.idDivision asc");
        cb_divisionCrear.removeAllItems();
        for (Object object : resultList_division) {
            Division d = (Division) object;
            cb_divisionCrear.addItem(d.getNombre());
        }

    }//GEN-LAST:event_bCrearDivisionActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        if (pos == -1 || modfNombre.getText().equals("")) {
            return;
        }

        String valor = tablaModfDep.getValueAt(tablaModfDep.getSelectedRow(), 1).toString();//1 por el nombre
        if (JOptionPane.showConfirmDialog(null, "¿Está seguro de modificar el"
                + " Departamento " + valor + "?", "Información", JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION) {

            int posOr = this.pos;
            Departamento d = (Departamento) resultList_departamento.get(posOr);
            d.setNombre(modfNombre.getText());
            d.setIdDivision((Division) resultList_division.get(cb_divisionModificar.getSelectedIndex()));
            ObjectModelDAO.updateObject(d);

            resultList_division = ObjectModelDAO.getResultQuery("FROM Division d order by d.idDivision asc");
            cb_divisionModificar.removeAllItems();
            for (Object object : resultList_division) {
                Division div = (Division) object;
                cb_divisionModificar.addItem(div.getNombre());
            }
            String sql = "FROM Departamento d order by d.idDepartamento asc";
            resultList_departamento = ObjectModelDAO.getResultQuery(sql);
            JavaUtil.displayResult(resultList_departamento, tablaModfDep);
            tablaModfDep.setEditable(false);
            tablaModfDep.setRowSelectionInterval(posOr, posOr);
        }
    }//GEN-LAST:event_bModificarActionPerformed

    private void bCrearDivision1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearDivision1ActionPerformed
        createJDialogGeneric(new JPdivision(1));
    }//GEN-LAST:event_bCrearDivision1ActionPerformed

    private void bDelet_depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDelet_depActionPerformed
        if (pos == -1) {
            return;
        }

        String valor = tablaDeletDep.getValueAt(tablaDeletDep.getSelectedRow(), tablaDeletDep.getSelectedColumn()).toString();
        if (JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar el"
                + " Departamento " + valor + "?", "Información", JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION) {

            ObjectModelDAO.deleteObject(resultList_departamento.get(pos));
            String sql = "FROM Departamento d order by d.idDepartamento asc";
            resultList_departamento = ObjectModelDAO.getResultQuery(sql);
            JavaUtil.displayResult(resultList_departamento, tablaDeletDep);
            pos = -1;
            tablaDeletDep.setEditable(false);
        }
    }//GEN-LAST:event_bDelet_depActionPerformed

    private void panelScrudDepStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_panelScrudDepStateChanged

        if (panelScrudDep.getTabCount() != 4) {
            return;
        }

        //verifica si debe abrir un panel desde la llamada
        if (this.tabCrud != null) {
            int tabCrud = this.tabCrud.intValue();
            this.tabCrud = null;
            panelScrudDep.setSelectedIndex(tabCrud);
            return;
        }

        if (panelScrudDep.getSelectedIndex() == 0) {
            String sql = "FROM Departamento d order by d.idDepartamento asc";
            List resultList = ObjectModelDAO.getResultQuery(sql);

            JavaUtil.displayResult(resultList, listadoDepartamentos);
            listadoDepartamentos.setEditable(false);
        }

        if (panelScrudDep.getSelectedIndex() == 1) {
            nuevDep.setText("");
            resultList_division = ObjectModelDAO.getResultQuery("FROM Division d order by d.idDivision asc");
            cb_divisionCrear.removeAllItems();
            for (Object object : resultList_division) {
                Division d = (Division) object;
                cb_divisionCrear.addItem(d.getNombre());
            }
            String sql = "FROM Departamento d order by d.idDepartamento asc";
            resultList_departamento = ObjectModelDAO.getResultQuery(sql);
            JavaUtil.displayResult(resultList_departamento, tablaCrearDepartamento);
            tablaCrearDepartamento.setEditable(false);
        }

        if (panelScrudDep.getSelectedIndex() == 2) {
            idDepartamento.setText("");
            modfNombre.setText("");
            resultList_division = ObjectModelDAO.getResultQuery("FROM Division d order by d.idDivision asc");
            cb_divisionModificar.removeAllItems();
            for (Object object : resultList_division) {
                Division d = (Division) object;
                cb_divisionModificar.addItem(d.getNombre());
            }
            String sql = "FROM Departamento d order by d.idDepartamento asc";
            resultList_departamento = ObjectModelDAO.getResultQuery(sql);
            JavaUtil.displayResult(resultList_departamento, tablaModfDep);
            tablaModfDep.setEditable(false);
            pos = -1;
            cb_divisionModificar.setSelectedIndex(pos);

        }

        if (panelScrudDep.getSelectedIndex() == 3) {
            String sql = "FROM Departamento d order by d.idDepartamento asc";
            resultList_departamento = ObjectModelDAO.getResultQuery(sql);

            JavaUtil.displayResult(resultList_departamento, tablaDeletDep);
            pos = -1;
            tablaDeletDep.setEditable(false);
        }
    }//GEN-LAST:event_panelScrudDepStateChanged

    private void generarReporte() {
        try {
            JasperPrint jasperPrint = null;
            Map<String, Object> parametro = new HashMap<>();

            TableModelReport dataSourse = new TableModelReport(listadoDepartamentos.getModel());

            parametro.put("REPORT_DATA_SOURSE", dataSourse);
            JasperReport reporte = (JasperReport) JRLoader.loadObject(this.getClass().getResourceAsStream(rutaJasper));
            jasperPrint = JasperFillManager.fillReport(reporte, null, dataSourse);
            JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);
            jasperViewer.setTitle("Reporte de Clasificación de Producto");
            jasperViewer.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error" + e);
        }
    }

    private void bt_GenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_GenerarReporteActionPerformed
        generarReporte();
    }//GEN-LAST:event_bt_GenerarReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCrear;
    private javax.swing.JButton bCrearDivision;
    private javax.swing.JButton bCrearDivision1;
    private javax.swing.JButton bDelet_dep;
    private javax.swing.JButton bModificar;
    private javax.swing.JButton bt_GenerarReporte;
    private javax.swing.JComboBox cb_divisionCrear;
    private javax.swing.JComboBox cb_divisionModificar;
    private javax.swing.JLabel idDepartamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private org.jdesktop.swingx.JXTable listadoDepartamentos;
    private javax.swing.JTextField modfNombre;
    private javax.swing.JTextField nuevDep;
    private javax.swing.JTabbedPane panelScrudDep;
    private org.jdesktop.swingx.JXTable tablaCrearDepartamento;
    private org.jdesktop.swingx.JXTable tablaDeletDep;
    private org.jdesktop.swingx.JXTable tablaModfDep;
    // End of variables declaration//GEN-END:variables
}
