/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.paneles;

import clases.csv.CSVreader;
import gui.dialogos.JDbackupDB;
import hibernate.DAO.ObjectModelDAO;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelos.mapeos.Almacen;
import util.JavaUtil;
import static util.JavaUtil.cons_seleccionar;

/**
 *
 * @author Pablo
 */
public class JPexportData extends javax.swing.JPanel {

    private CSVreader csvReader;
    private int pos_tienda;
    private List tiendas;

    /**
     * Creates new form JPexportData
     */
    public JPexportData() {
        initComponents();
        cargarCB();
        busy.setEnabled(false);
        busy.setVisible(false);
        busy.setBusy(false);
    }

    private void cargarCB() {
        try {
            tiendas = ObjectModelDAO.getResultQuery("from Almacen a order by a.idAlmacen asc");
            cb_tienda.removeAllItems();
            cb_tienda.addItem(cons_seleccionar);

            for (Object object : tiendas) {
                Almacen a = (Almacen) object;
                cb_tienda.addItem(a.getNombre());
            }
            pos_tienda = -1;

        } catch (Exception e) {
            Logger.getLogger(JPexportData.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(null, "ERROR AL CARGAR ComBox : " + e);
            System.err.println("ERROR AL CARGAR ComBox : " + e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filesc = new javax.swing.JFileChooser();
        jPanel3 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        AbrirArchivoBoton_ = new javax.swing.JButton();
        jXButton2 = new org.jdesktop.swingx.JXButton();
        GenerarArchivoBoton = new org.jdesktop.swingx.JXButton();
        jComboBoxTipoExport = new javax.swing.JComboBox();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        cb_tienda = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jXButton1 = new org.jdesktop.swingx.JXButton();
        busy = new org.jdesktop.swingx.JXBusyLabel();
        panel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        archivo = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        exportarBD = new javax.swing.JButton();

        filesc.setApproveButtonToolTipText("");
        filesc.setControlButtonsAreShown(false);
        filesc.setCurrentDirectory(new java.io.File("\\\\192.2.1.70\\SistemaMiyake\\exportScript"));

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Exportacion de Datos. "));

        AbrirArchivoBoton_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_almacen/ayuda.png"))); // NOI18N
        AbrirArchivoBoton_.setText("Abrir Archivo");
        AbrirArchivoBoton_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirArchivoBoton_ActionPerformed(evt);
            }
        });

        jXButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_almacen/1417212535_Forward.png"))); // NOI18N
        jXButton2.setText("Enviar Por Email");
        jXButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton2ActionPerformed(evt);
            }
        });

        GenerarArchivoBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_almacen/1416789780_database_gear.png"))); // NOI18N
        GenerarArchivoBoton.setText("Generar Archivo");
        GenerarArchivoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarArchivoBotonActionPerformed(evt);
            }
        });

        jComboBoxTipoExport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Generar Por BarCode", "Generar Por Descuento", "Generar Por Producto" }));

        jXLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_almacen/tipo.png"))); // NOI18N
        jXLabel1.setText("Tipo de Exportacion");

        cb_tienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tiendaActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_almacen/desde.png"))); // NOI18N
        jLabel9.setText("Seleccione Tienda");

        jXButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_almacen/reiniciar.png"))); // NOI18N
        jXButton1.setText("Reiniciar");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTipoExport, 0, 1, Short.MAX_VALUE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_tienda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GenerarArchivoBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AbrirArchivoBoton_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AbrirArchivoBoton_)
                    .addComponent(cb_tienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jXButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenerarArchivoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTipoExport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );
        jLayeredPane1.setLayer(AbrirArchivoBoton_, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jXButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(GenerarArchivoBoton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jComboBoxTipoExport, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jXLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cb_tienda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jXButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        busy.setText("CARGANDO...!!!");

        panel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Deatalles de Exportacion"));

        jTabbedPane2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane2StateChanged(evt);
            }
        });

        ta1.setColumns(20);
        ta1.setRows(5);
        jScrollPane6.setViewportView(ta1);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Vizualizar", jPanel12);

        archivo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel23.setText("Detalle");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jTabbedPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(archivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25))))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(archivo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        exportarBD.setText("Exportar BD");
        exportarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarBDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane1))
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(busy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(exportarBD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exportarBD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane2StateChanged
        //        if (jTabbedPane2.getSelectedIndex() == 2) {
        //            ta2.setText(csvReader.procesCSV().toString());
        //        }
    }//GEN-LAST:event_jTabbedPane2StateChanged

    private void AbrirArchivoBoton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirArchivoBoton_ActionPerformed
//        int index = tabpanel.getSelectedIndex();

        if (filesc.getChoosableFileFilters().length > 1) {
            filesc.removeChoosableFileFilter(filesc.getChoosableFileFilters()[1]);
        }
        filesc.setFileFilter(new FileNameExtensionFilter("Archivos txt ", "txt"));

        int returnVal = filesc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                File file = filesc.getSelectedFile();
                archivo.setText(file.getAbsolutePath());

                csvReader = new CSVreader(file.getAbsolutePath());
                ta1.read(new FileReader(file.getAbsolutePath()), null);

            } catch (IOException ex) {
                Logger.getLogger(JPexportData.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "ERROR AL Abrir Archivo : " + ex);
                System.err.println("ERROR AL Abrir Archivo : " + ex);
            }

        } else {
            archivo.setText("");
        }
    }//GEN-LAST:event_AbrirArchivoBoton_ActionPerformed

    private void jXButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton2ActionPerformed

        EnviosEmail e = new EnviosEmail();
        e.setVisible(true);

    }//GEN-LAST:event_jXButton2ActionPerformed

    private void GenerarArchivoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarArchivoBotonActionPerformed

        Thread hilo = new Thread() {

            @Override
            public void run() {
                try {
                    busy.setEnabled(true);
                    busy.setVisible(true);
                    busy.setBusy(true);

                    int tipo = jComboBoxTipoExport.getSelectedIndex();
                    System.err.println("tipo valor : " + tipo);
                    switch (tipo) {
                        case 1: // Generar archivos por codigo de barras
                            String nombreFileCodeBar = JOptionPane.showInputDialog(null, "Introduc Nombre del Archivo");

                            String SQLDB = "COPY (SELECT "
                                    + " 0 as az, "
                                    + " 2 as ay,  "
                                    + " REPLICATE(' ', 7) || inventario_tienda.id_producto  As Sku,  "
                                    + "REPLICATE(' ', 7) || inventario_tienda.id_producto As Barra, "
                                    + "0 as ab,0 as ac,0 as ad,0 as ae "
                                    + "FROM  "
                                    + "  public.producto,  "
                                    + "  public.clasificacion,  "
                                    + "  public.division,  "
                                    + "  public.inventario_tienda,  "
                                    + "  public.departamento "
                                    + "WHERE  "
                                    + "  producto.id_producto = inventario_tienda.id_producto AND "
                                    + "  producto.id_clasificacion = clasificacion.id_clasificacion AND "
                                    + "  clasificacion.id_departamento = departamento.id_departamento AND "
                                    + "  departamento.id_division = division.id_division AND "
                                    + "  division.id_division<>9 AND "
                                    + "  producto.descripcion not like ' ' AND "
                                    //+ "  inventario_tienda.precio_con_descuento>=0.05 ) TO '" + System.getProperty("user.home") + "\\" + nombreFileCodeBar + "' WITH DELIMITER AS ',' ";
                                    + "  inventario_tienda.precio_con_descuento>=0.05 ) TO 'C:\\SistemaMiyake\\exportScript\\" + nombreFileCodeBar + "' WITH DELIMITER AS ',' ";

                            ObjectModelDAO.executeQueryString(SQLDB);
                            break;

                        case 2:// Generar archivos por Decuento
                            String nombreFile = JOptionPane.showInputDialog(null, "Introduc Nombre del Archivo");
                            String SQL = "COPY (SELECT  "
                                    + "  0 as a,1 as b, "
                                    + "  REPLICATE(' ', 7)||inventario_tienda.id_producto AS codigo,  "
                                    + "  LTRIM(replace(producto.descripcion,',',' '))  AS descr,  "
                                    + "  REPLICATE(' ', 3)||producto.id_clasificacion  AS depart,   "
                                    + "  round( CAST(producto.precio_original as numeric), 0) As precio, "
                                    + "  1312173000 as Desde,  "
                                    + "  round( CAST(inventario_tienda.precio_con_descuento as numeric), 0) As descuento, "
                                    + "  13200035400 as Hasta, "
                                    + "  8 as d,4 as e,0 as f,0 as g,65 as h,' ' as i, ' ' as j,  "
                                    + "  0 as a1,  0 as a2, 0 as a3, 0 as a4, 0 as a5, 0 as a6, 0 as a7, 0 as a8,  "
                                    + "  ' ' as b1,0 as b2, 3 as b3, 0 as c1, 0 as c2, 0 as c3, 0 as c4, 0 as c5 "
                                    + "FROM  "
                                    + "  public.inventario_tienda,  "
                                    + "  public.producto,  "
                                    + "  public.clasificacion,  "
                                    + "  public.division,  "
                                    + "  public.departamento "
                                    + "WHERE  "
                                    + "  inventario_tienda.id_producto = producto.id_producto AND "
                                    + "  producto.id_clasificacion = clasificacion.id_clasificacion AND "
                                    + "  clasificacion.id_departamento = departamento.id_departamento AND "
                                    + "  departamento.id_division = division.id_division AND "
                                    + "  inventario_tienda.precio_con_descuento>0.05 and public.division.id_division<>9 and producto.descripcion not like ' ' and "
                                    + "  inventario_tienda.id_almacen = 2 "
                                    + "  Order by producto.id_producto ) TO 'C:\\SistemaMiyake\\exportScript\\" + nombreFile + "' WITH DELIMITER AS ',' ";
                            ObjectModelDAO.executeQueryString(SQL);
                            break;

                    }

                    busy.setEnabled(false);
                    busy.setVisible(false);
                    busy.setBusy(false);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "ERROR Generando Archivos :" + e);
                    System.err.println("ERROR Generando Archivos :" + e);
                    Logger.getLogger(JPexportData.class.getName()).log(Level.SEVERE, null, e);
                }

            }
        };
        hilo.start();

    }//GEN-LAST:event_GenerarArchivoBotonActionPerformed

    private void cb_tiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tiendaActionPerformed
        //        if (!((String) cb_tienda.getSelectedItem()).equals(cons_seleccionar)) {
        //            pos_tienda = cb_tienda.getSelectedIndex() - 1;
        //        } else {
        //            pos_tienda = -1;
        //        }
    }//GEN-LAST:event_cb_tiendaActionPerformed

    private void exportarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarBDActionPerformed
        JDbackupDB jdbackUP = new JDbackupDB(null, true);
        jdbackUP.setVisible(true);
    }//GEN-LAST:event_exportarBDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbrirArchivoBoton_;
    private org.jdesktop.swingx.JXButton GenerarArchivoBoton;
    private javax.swing.JLabel archivo;
    private org.jdesktop.swingx.JXBusyLabel busy;
    private javax.swing.JComboBox cb_tienda;
    private javax.swing.JButton exportarBD;
    private javax.swing.JFileChooser filesc;
    private javax.swing.JComboBox jComboBoxTipoExport;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private org.jdesktop.swingx.JXButton jXButton1;
    private org.jdesktop.swingx.JXButton jXButton2;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private javax.swing.JPanel panel1;
    private javax.swing.JTextArea ta1;
    // End of variables declaration//GEN-END:variables
}
