/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.paneles;

import com.healthmarketscience.jackcess.ColumnBuilder;
import com.healthmarketscience.jackcess.Database;
import com.healthmarketscience.jackcess.DatabaseBuilder;
import com.healthmarketscience.jackcess.Table;
import com.healthmarketscience.jackcess.TableBuilder;
import hibernate.DAO.ObjectModelDAO;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import modelos.mapeos.Almacen;
import modelos.mapeos.InventarioTienda;
import modelos.mapeos.Producto;
import modelos.mapeos.SalidaParaTiendaDetalle;
import util.JavaUtil;
import static util.JavaUtil.setTableCellAlignment;

/**
 *
 * @author Laura
 */
public class JPimprimirEtiquetaParticular extends javax.swing.JPanel {

    private List resultListFinal = new ArrayList();
    private List resultListAlmacen;
    private int pos;
    private InventarioTienda ivt = new InventarioTienda();

    public JPimprimirEtiquetaParticular() {
        initComponents();
        setTableCellAlignment(JLabel.CENTER, listadoProductosADescontar);
        listadoProductosADescontar.getTableHeader().setReorderingAllowed(false);
        SetCb();

        listadoProductosADescontar.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent lse) {
                if (!lse.getValueIsAdjusting()) {

                    pos = listadoProductosADescontar.getSelectedRow();
                    if (pos == -1) {
                        return;
                    }

                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb_Tiend_Inv_Part = new javax.swing.JComboBox();
        lb_Tiend = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listadoProductosADescontar = new org.jdesktop.swingx.JXTable();
        btn_imprimirEtiquetas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        cb_Tiend_Inv_Part.setPreferredSize(new java.awt.Dimension(58, 23));

        lb_Tiend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_almacen/1417636330_store.png"))); // NOI18N
        lb_Tiend.setText("Tienda:");

        listadoProductosADescontar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "REFERENCIA", "DESCRIPCION", "PRECIO CON DESCUENTO", "CANTIDAD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listadoProductosADescontar.setToolTipText("Presionar TAB luego de ingresar el código. Flecha abajo luego de ingresar cantidad.");
        listadoProductosADescontar.setHorizontalScrollEnabled(true);
        listadoProductosADescontar.setSortable(false);
        listadoProductosADescontar.getTableHeader().setReorderingAllowed(false);
        listadoProductosADescontar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                listadoProductosADescontarKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(listadoProductosADescontar);

        btn_imprimirEtiquetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/inventario.png"))); // NOI18N
        btn_imprimirEtiquetas.setText("Imprimir Etiquetas");
        btn_imprimirEtiquetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirEtiquetasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Listado de Productos para Imprimir Etiquetas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_Tiend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_Tiend_Inv_Part, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_imprimirEtiquetas))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 123, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(0, 123, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_Tiend_Inv_Part, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_Tiend)
                    .addComponent(btn_imprimirEtiquetas))
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SetCb() {
        resultListAlmacen = ObjectModelDAO.getResultQuery("FROM Almacen a order by a.idAlmacen asc");
        cb_Tiend_Inv_Part.removeAllItems();
        for (Object object : resultListAlmacen) {
            Almacen a = (Almacen) object;
            cb_Tiend_Inv_Part.addItem(a.getNombre());
        }
    }
    private void btn_imprimirEtiquetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirEtiquetasActionPerformed

        if (resultListFinal.isEmpty()) {
            return;
        }

        String filePath = "C:/Etiquetado Bulto Miyake/Imprime.bat";
        //String filePath = "\\\\MIYAKE-FACTURA\\Etiquetado Bulto Miyake/Imprime.bat";
        try {
            createMDB();
            Process p = Runtime.getRuntime().exec(filePath);
            JOptionPane.showMessageDialog(this, "Se han generado las etiquetas..");
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_btn_imprimirEtiquetasActionPerformed

    private void createMDB() throws IOException, SQLException {
        File archivo = new File("C:/Etiquetado Bulto Miyake/Etiquetas.mdb");
       // File archivo = new File("C:/prueba/Etiquetas.mdb");
        //File archivo = new File("\\\\MIYAKE-FACTURA\\Etiquetado Bulto Miyake/Etiquetas.mdb3"); 
        ///Etiquetado Bulto Miyake/

        if (archivo.exists()) {
            archivo.delete();
        }

        archivo.createNewFile();
        Database db = DatabaseBuilder.create(Database.FileFormat.V2000, archivo);
        Table newTable = new TableBuilder("Tbl_Etiquetas")
                .addColumn(new ColumnBuilder("CodigoProducto")
                        .setSQLType(Types.NUMERIC))
                .addColumn(new ColumnBuilder("Referencia")
                        .setSQLType(Types.VARCHAR))
                .addColumn(new ColumnBuilder("DescripcionProducto")
                        .setSQLType(Types.VARCHAR))
                .addColumn(new ColumnBuilder("PrecioVenta")
                        .setSQLType(Types.FLOAT))
                .addColumn(new ColumnBuilder("CostoDolar")//siempre 0
                        .setSQLType(Types.NUMERIC))
                .addColumn(new ColumnBuilder("CodigoProveedor")
                        .setSQLType(Types.VARCHAR))
                .addColumn(new ColumnBuilder("Mes")
                        .setSQLType(Types.VARCHAR))
                .addColumn(new ColumnBuilder("Anno")
                        .setSQLType(Types.VARCHAR))
                .addColumn(new ColumnBuilder("TextoZona")//siempre vacio
                        .setSQLType(Types.VARCHAR))
                .addColumn(new ColumnBuilder("Cantidad")//siempre 1
                        .setSQLType(Types.NUMERIC))
                .addColumn(new ColumnBuilder("Adicional")//siempre vacio
                        .setSQLType(Types.VARCHAR))
                .addColumn(new ColumnBuilder("Marca")
                        .setSQLType(Types.VARCHAR))
                .addColumn(new ColumnBuilder("PrecioVentasi")
                        .setSQLType(Types.FLOAT))
                .toTable(db);

        Calendar now = Calendar.getInstance();

        for (Object o : resultListFinal) {
            InventarioTienda ivt = (InventarioTienda) o;
            int cantElem = ivt.getCantidad();

            Producto produc = ivt.getProducto();
            Integer id = produc.getIdProducto();
            String referencia = produc.getReferenciaProducto();
            String descripcion = produc.getDescripcion();
            Double precioCI = (ivt.getPrecioConDescuento() + (ivt.getPrecioConDescuento() * JavaUtil.iva));
            Integer idproveedor = produc.getIdProveedor() == null ? null : produc.getIdProveedor().getIdProveedor();
            String marca = produc.getIdMarca() == null ? "" : produc.getIdMarca().getNombre();
            Float precioSI = ivt.getPrecioConDescuento();
            for (int i = 0; i < cantElem; i++) {

                newTable.addRow(
                        id,
                        referencia,
                        descripcion,
                        precioCI,
                        0,
                        idproveedor + "",
                        now.get(Calendar.MONTH) + 1,
                        now.get(Calendar.YEAR),
                        "",
                        1,
                        "",
                        marca,
                        precioSI
                );
            }

        }
    }

    boolean codigorepetido(Object cod) {

        for (int i = 0; i < listadoProductosADescontar.getRowCount() - 1; i++) {
            if (listadoProductosADescontar.getValueAt(i, 0).equals(cod)) {
                return true;
            }
        }
        return false;
    }


    private void listadoProductosADescontarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listadoProductosADescontarKeyReleased

        if (pos == -1) {
            return;
        }
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {

            if (listadoProductosADescontar.getModel().getValueAt(pos, 2) == null
                    || listadoProductosADescontar.getModel().getValueAt(pos, 3) == null) {
                JOptionPane.showMessageDialog(null, "Todos los campos deben estar completos");
                return;
            }
            if (listadoProductosADescontar.getModel().getValueAt(pos, 4) == null) {
                JOptionPane.showMessageDialog(null, "Ingrese la cantidad");
                //listadoProductosADescontar.setColumnSelectionInterval(0, 0);
                return;
            }
            int cantidadingresada = Integer.parseInt(listadoProductosADescontar.getModel().getValueAt(pos, 4).toString());
            if (cantidadingresada<=0) {
                JOptionPane.showMessageDialog(null, "La cantidad debe ser mayor a cero");
                return;
            } else {
                ivt.setCantidad(cantidadingresada);
                resultListFinal.add(ivt);

                int rowCount = listadoProductosADescontar.getRowCount();
                int rowSelected = listadoProductosADescontar.getSelectedRow();
                //si la fila seleccionada es la ultima
                if (rowSelected == rowCount - 1) {//0 hasta n-1
                    ((DefaultTableModel) listadoProductosADescontar.getModel()).addRow(new Object[listadoProductosADescontar.getColumnCount()]);
                    //se agrego una nueva asi que si se toma en cuenta n
                    listadoProductosADescontar.setRowSelectionInterval(rowCount, rowCount);
                    listadoProductosADescontar.setColumnSelectionInterval(0, 0);
                }
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {

            int codigoingresado = Integer.parseInt(listadoProductosADescontar.getValueAt(pos, 0).toString());
            Almacen almacenseleccionado = (Almacen) resultListAlmacen.get(cb_Tiend_Inv_Part.getSelectedIndex());

            if (listadoProductosADescontar.getRowCount() >= 2) {
                if (codigorepetido(codigoingresado)) {
                    JOptionPane.showMessageDialog(null, "El Código ya se encuentra en el listado");
                    return;
                } else {
                    String sql = "FROM InventarioTienda i WHERE i.inventarioTiendaPK.idProducto = " + codigoingresado
                            + " AND i.inventarioTiendaPK.idAlmacen = " + almacenseleccionado.getIdAlmacen();
                    List resultList = ObjectModelDAO.getResultQuery(sql);

                    if (resultList.isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Código no encontrado, Verifique e Inténtelo nuevamente");
                        return;
                    }

                    ivt = (InventarioTienda) resultList.get(0);

                    listadoProductosADescontar.getModel().setValueAt(ivt.getProducto().getReferenciaProducto(), pos, 1);
                    listadoProductosADescontar.getModel().setValueAt(ivt.getProducto().getDescripcion(), pos, 2);
                    listadoProductosADescontar.getModel().setValueAt(ivt.getPrecioConDescuento(), pos, 3);
                    listadoProductosADescontar.setColumnSelectionInterval(4, 4);
                }
            } else {
                String sql = "FROM InventarioTienda i WHERE i.inventarioTiendaPK.idProducto = " + codigoingresado
                        + " AND i.inventarioTiendaPK.idAlmacen = " + almacenseleccionado.getIdAlmacen();
                List resultList = ObjectModelDAO.getResultQuery(sql);

                if (resultList.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Código no encontrado, Verifique e Inténtelo nuevamente");
                    return;
                }

                ivt = (InventarioTienda) resultList.get(0);

                listadoProductosADescontar.getModel().setValueAt(ivt.getProducto().getReferenciaProducto(), pos, 1);
                listadoProductosADescontar.getModel().setValueAt(ivt.getProducto().getDescripcion(), pos, 2);
                listadoProductosADescontar.getModel().setValueAt(ivt.getPrecioConDescuento(), pos, 3);
                listadoProductosADescontar.setColumnSelectionInterval(4, 4);
            }
        }

        //si le da a delete
        if (evt.getKeyCode() == KeyEvent.VK_DELETE
                && JOptionPane.showConfirmDialog(null, "Desea eliminar el renglón?",
                        "Advertencia", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

            resultListFinal.remove(listadoProductosADescontar.getSelectedRow());
            ((DefaultTableModel) listadoProductosADescontar.getModel()).removeRow(listadoProductosADescontar.getSelectedRow());
        }
    }//GEN-LAST:event_listadoProductosADescontarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_imprimirEtiquetas;
    private javax.swing.JComboBox cb_Tiend_Inv_Part;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_Tiend;
    private org.jdesktop.swingx.JXTable listadoProductosADescontar;
    // End of variables declaration//GEN-END:variables
}
