/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.paneles;

import util.JavaUtil;
import static util.JavaUtil.createJDialogGeneric;
import static util.JavaUtil.setTableCellAlignment;
import hibernate.DAO.ObjectModelDAO;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import modelos.mapeos.Contacto;
import modelos.mapeos.Proveedor;
import modelos.tablas.TableModelReport;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

public class JPproveedor extends javax.swing.JPanel {

    private List resultListContactos;
    private List resultListProveedores;
    private int pos;
    public final String rutaJasper = "/reportes/ReporteProveedores.jasper";
    DefaultTableModel tableModel;
    private Integer tabCrud;

    public JPproveedor() {
        this(0);
    }

    public JPproveedor(Integer tabCrud) {
        this.tabCrud = tabCrud;
        initComponents();

        setTableCellAlignment(JLabel.CENTER, listadoProveedores);
        setTableCellAlignment(JLabel.CENTER, tablaModfProveedor);
        setTableCellAlignment(JLabel.CENTER, tablaDeletProveedor);
        listadoProveedores.getTableHeader().setReorderingAllowed(false);
        tablaModfProveedor.getTableHeader().setReorderingAllowed(false);
        tablaDeletProveedor.getTableHeader().setReorderingAllowed(false);

        tablaModfProveedor.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent lse) {
                if (!lse.getValueIsAdjusting()) {

                    pos = tablaModfProveedor.getSelectedRow();
                    if (pos == -1) {
                        return;
                    }
                    Proveedor p = (Proveedor) resultListProveedores.get(pos);

                    fieldNomb.setText(p.getNombre());
                    fieldTlf1.setText(p.getTelefono1());
                    fieldTlf2.setText(p.getTelefono2());
                    fieldFax.setText(p.getFax());
                    fieldPostal.setText(p.getCodPostal());
                    fieldCorreo.setText(p.getEmail());
//                    fieldGerente.setText(c.getNombre());
//                    fieldContacto1.setText(c.getNombre());
//                    fieldContacto2.setText(c.getNombre());
                    cb_gerente1.setSelectedItem(p.getIdContactoGerente() == null ? null : p.getIdContactoGerente().getNombre());
                    cb_contacto1.setSelectedItem(p.getIdContacto1() == null ? null : p.getIdContacto1().getNombre());
                    cb_contacto2.setSelectedItem(p.getIdContacto2() == null ? null : p.getIdContacto2().getNombre());

                }
            }
        });

        tablaDeletProveedor.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent lse) {
                if (!lse.getValueIsAdjusting()) {

                    if (tablaDeletProveedor.getSelectedRow() == -1) {
                        return;
                    }
                    pos = tablaDeletProveedor.getSelectedRow();

                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelScrudProveedor = new javax.swing.JTabbedPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listadoProveedores = new org.jdesktop.swingx.JXTable();
        jLabel17 = new javax.swing.JLabel();
        bt_GenerarReporteProveedores = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldNombProv = new javax.swing.JTextField();
        bCrearProveedor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fieldTlf1Prov = new javax.swing.JTextField();
        fieldTlf2Prov = new javax.swing.JTextField();
        fieldFaxProv = new javax.swing.JTextField();
        fieldCorreoProv = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fieldPostalProv = new javax.swing.JTextField();
        cb_gerente = new javax.swing.JComboBox();
        cb_contacto = new javax.swing.JComboBox();
        cb_otrocontacto = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaModfProveedor = new org.jdesktop.swingx.JXTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        fieldNomb = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fieldTlf1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        fieldTlf2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        fieldFax = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        fieldPostal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        fieldCorreo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cb_gerente1 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        cb_contacto1 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        cb_contacto2 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        bModfProve = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        bEliminarProveedor = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaDeletProveedor = new org.jdesktop.swingx.JXTable();
        jLabel21 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(700, 403));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        panelScrudProveedor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                panelScrudProveedorStateChanged(evt);
            }
        });

        listadoProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Telefono 1", "Telefono 2", "Fax", "Código Postal", "Correo", "Gerente", "Contacto", "Otro Contacto", "Fecha de Creación", "Fecha de Modificación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listadoProveedores.setHorizontalScrollEnabled(true);
        listadoProveedores.setPreferredSize(new java.awt.Dimension(5, 5));
        listadoProveedores.setSortable(false);
        jScrollPane1.setViewportView(listadoProveedores);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1416622346_xmag.png"))); // NOI18N
        jLabel17.setText("Para realizar Busqueda: Haga Click en la tabla + CTRL F");

        bt_GenerarReporteProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/reportproveedor.png"))); // NOI18N
        bt_GenerarReporteProveedores.setText("Generar Reporte");
        bt_GenerarReporteProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_GenerarReporteProveedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(bt_GenerarReporteProveedores)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 483, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(bt_GenerarReporteProveedores))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane5.setViewportView(jPanel1);

        panelScrudProveedor.addTab("Consultar", jScrollPane5);

        jPanel2.setAutoscrolls(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/proveedor.png"))); // NOI18N
        jLabel1.setText("Nombre:     ");

        bCrearProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1418875864_testimonials.png"))); // NOI18N
        bCrearProveedor.setText("CrearProveedor");
        bCrearProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearProveedorActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/telefono2.png"))); // NOI18N
        jLabel2.setText("Telefono 1:");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/telefono2.png"))); // NOI18N
        jLabel3.setText("Telefono 2:");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fax.png"))); // NOI18N
        jLabel4.setText("Fax:                     ");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/correo.png"))); // NOI18N
        jLabel5.setText("Correo:");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gerente.png"))); // NOI18N
        jLabel6.setText("Nombre del Gerente:");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/contacto.png"))); // NOI18N
        jLabel7.setText("Nombre de Contacto:");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/otrouser.png"))); // NOI18N
        jLabel8.setText("Otro Contacto:");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/codepostal.png"))); // NOI18N
        jLabel9.setText("Código Postal:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1415663093_add-user.png"))); // NOI18N
        jButton1.setText("Crear Contacto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldTlf1Prov, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldNombProv, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(fieldTlf2Prov, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldPostalProv, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fieldFaxProv, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fieldCorreoProv, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6))
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_otrocontacto, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_gerente, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(414, 414, 414))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addComponent(bCrearProveedor)
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addGap(658, 658, 658))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldNombProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldTlf1Prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldTlf2Prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fieldFaxProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPostalProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCorreoProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb_gerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cb_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cb_otrocontacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCrearProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addGap(28, 28, 28))
        );

        jScrollPane4.setViewportView(jPanel2);

        panelScrudProveedor.addTab("Crear", jScrollPane4);

        jPanel3.setLayout(new java.awt.BorderLayout());

        tablaModfProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Telefono 1", "Telefono 2", "Fax", "Código Postal", "Correo", "Gerente", "Contacto", "Otro Contacto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaModfProveedor.setHorizontalScrollEnabled(true);
        tablaModfProveedor.setSortable(false);
        jScrollPane2.setViewportView(tablaModfProveedor);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel5.setAutoscrolls(true);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/proveedor.png"))); // NOI18N
        jLabel10.setText("Nombre:");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/telefono2.png"))); // NOI18N
        jLabel11.setText("Telefono 1:");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/telefono2.png"))); // NOI18N
        jLabel12.setText("Telefono 2:");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fax.png"))); // NOI18N
        jLabel13.setText("Fax:");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/codepostal.png"))); // NOI18N
        jLabel18.setText("Código Postal:");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/correo.png"))); // NOI18N
        jLabel14.setText("Correo:");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gerente.png"))); // NOI18N
        jLabel15.setText("Nombre del Gerente:");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/contacto.png"))); // NOI18N
        jLabel16.setText("Nombre de Contacto:");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/otrouser.png"))); // NOI18N
        jLabel19.setText("Otro Contacto:");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1415663093_add-user.png"))); // NOI18N
        jButton2.setText("Crear Contacto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        bModfProve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1415656862_Circulation.png"))); // NOI18N
        bModfProve.setText("Modificar");
        bModfProve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModfProveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldTlf1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldTlf2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldFax, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_gerente1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_contacto1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_contacto2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bModfProve)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fieldNomb)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldNomb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldTlf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldTlf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_gerente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addGap(16, 16, 16)
                .addComponent(cb_contacto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_contacto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(bModfProve, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, java.awt.BorderLayout.EAST);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1416622346_xmag.png"))); // NOI18N
        jLabel20.setText("Para realizar Busqueda: Haga Click en la tabla + CTRL F");
        jPanel3.add(jLabel20, java.awt.BorderLayout.PAGE_START);

        jScrollPane6.setViewportView(jPanel3);

        panelScrudProveedor.addTab("Modificar", jScrollPane6);

        bEliminarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1415657185_remove-sign-32.png"))); // NOI18N
        bEliminarProveedor.setText("Eliminar");
        bEliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarProveedorActionPerformed(evt);
            }
        });

        tablaDeletProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Telefono 1", "Telefono 2", "Fax", "Código Postal", "Correo", "Gerente", "Contacto", "Otro Contacto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDeletProveedor.setHorizontalScrollEnabled(true);
        tablaDeletProveedor.setSortable(false);
        jScrollPane3.setViewportView(tablaDeletProveedor);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1416622346_xmag.png"))); // NOI18N
        jLabel21.setText("Para realizar Busqueda: Haga Click en la tabla + CTRL F");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bEliminarProveedor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(bEliminarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jScrollPane7.setViewportView(jPanel4);

        panelScrudProveedor.addTab("Eliminar", jScrollPane7);

        add(panelScrudProveedor);
    }// </editor-fold>//GEN-END:initComponents

    private void bCrearProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearProveedorActionPerformed

        if (!fieldNombProv.getText().equals("") && !fieldTlf1Prov.getText().equals("")
                && !fieldTlf2Prov.getText().equals("") && !fieldCorreoProv.getText().equals("")
                && !fieldFaxProv.getText().equals("")) {
            if (JOptionPane.showConfirmDialog(this, "¿Está seguro de crear el"
                    + " nuevo proveedor con nombre : " + fieldNombProv.getText() + "?",
                    "Información", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                ObjectModelDAO.saveObject(new Proveedor(fieldNombProv.getText(), fieldTlf1Prov.getText(), fieldTlf2Prov.getText(),
                        fieldFaxProv.getText(), fieldPostalProv.getText(), fieldCorreoProv.getText(),
                        (Contacto) resultListContactos.get(cb_gerente.getSelectedIndex()), (Contacto) resultListContactos.get(cb_contacto.getSelectedIndex()),
                        (Contacto) resultListContactos.get(cb_otrocontacto.getSelectedIndex()))
                );
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");
        }
    }//GEN-LAST:event_bCrearProveedorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        createJDialogGeneric(new JPcontacto(1));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bModfProveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModfProveActionPerformed
        if (pos == -1 || fieldNomb.getText().equals("")) {
            return;
        }

        String valor = tablaModfProveedor.getValueAt(tablaModfProveedor.getSelectedRow(), 1).toString();//1 por el nombre
        if (JOptionPane.showConfirmDialog(null, "¿Está seguro de modificar el"
                + " Proveedor " + fieldNomb.getText() + "?", "Información", JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION) {

            int posOr = this.pos;
            Date fecha_modif = new Date();
            Proveedor p = (Proveedor) resultListProveedores.get(posOr);
            p.setNombre(fieldNomb.getText());
            p.setTelefono1(fieldTlf1.getText());
            p.setTelefono2(fieldTlf2.getText());
            p.setFax(fieldFax.getText());
            p.setCodPostal(fieldPostal.getText());
            p.setEmail(fieldCorreo.getText());
            p.setFechaModificacion(fecha_modif);
            p.setIdContactoGerente((Contacto) resultListContactos.get(cb_gerente1.getSelectedIndex()));
            p.setIdContacto1((Contacto) resultListContactos.get(cb_contacto1.getSelectedIndex()));
            p.setIdContacto2((Contacto) resultListContactos.get(cb_contacto2.getSelectedIndex()));
            ObjectModelDAO.updateObject(p);

            resultListContactos = ObjectModelDAO.getResultQuery("FROM Contacto c order by c.idContacto asc");
            cb_gerente1.removeAllItems();
            cb_contacto1.removeAllItems();
            cb_contacto2.removeAllItems();
            for (Object object : resultListContactos) {
                Contacto con = (Contacto) object;
                cb_gerente1.addItem(con.getNombre());
                cb_contacto1.addItem(con.getNombre());
                cb_contacto2.addItem(con.getNombre());
            }
            String sql = "FROM Proveedor p order by p.idProveedor asc";
            resultListProveedores = ObjectModelDAO.getResultQuery(sql);
            JavaUtil.displayResult(resultListProveedores, tablaModfProveedor);
            tablaModfProveedor.setEditable(false);
            tablaModfProveedor.setRowSelectionInterval(posOr, posOr);
        }
    }//GEN-LAST:event_bModfProveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        createJDialogGeneric(new JPcontacto(1));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bEliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarProveedorActionPerformed
        if (pos == -1) {
            return;
        }

        String valor = tablaDeletProveedor.getValueAt(tablaDeletProveedor.getSelectedRow(), tablaDeletProveedor.getSelectedColumn()).toString();
        if (JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar el"
                + " Proveedor " + fieldNomb.getText() + "?", "Información", JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION) {

            ObjectModelDAO.deleteObject(resultListProveedores.get(pos));
            String sql = "FROM Proveedor p order by p.idProveedor asc";
            resultListProveedores = ObjectModelDAO.getResultQuery(sql);
            JavaUtil.displayResult(resultListProveedores, tablaDeletProveedor);
            pos = -1;
            tablaDeletProveedor.setEditable(false);
        }
    }//GEN-LAST:event_bEliminarProveedorActionPerformed

    private void panelScrudProveedorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_panelScrudProveedorStateChanged

        if (panelScrudProveedor.getTabCount() != 4) {
            return;
        }

        //verifica si debe abrir un panel desde la llamada
        if (this.tabCrud != null) {
            int tabCrud = this.tabCrud.intValue();
            this.tabCrud = null;
            panelScrudProveedor.setSelectedIndex(tabCrud);
            return;
        }

        if (panelScrudProveedor.getSelectedIndex() == 0) {
            String sql = "FROM Proveedor p order by p.idProveedor asc";
            List resultList = ObjectModelDAO.getResultQuery(sql);

            JavaUtil.displayResult(resultList, listadoProveedores);
            listadoProveedores.setEditable(false);
        }

        if (panelScrudProveedor.getSelectedIndex() == 1) {
            fieldNombProv.setText("");
            fieldTlf1Prov.setText("");
            fieldTlf2Prov.setText("");
            fieldCorreoProv.setText("");
            fieldFaxProv.setText("");
            fieldPostalProv.setText("");
            resultListContactos = ObjectModelDAO.getResultQuery("FROM Contacto c order by c.idContacto asc");
            cb_gerente.removeAllItems();
            // cb_contacto.removeAllItems();
            // cb_otrocontacto.removeAllItems();
            for (Object object : resultListContactos) {
                Contacto c = (Contacto) object;
                cb_gerente.addItem(c.getNombre());
                cb_contacto.addItem(c.getNombre());
                cb_otrocontacto.addItem(c.getNombre());
            }
        }
        if (panelScrudProveedor.getSelectedIndex() == 2) {
            fieldNomb.setText("");
            fieldTlf1.setText("");
            fieldTlf2.setText("");
            fieldCorreo.setText("");
            fieldFax.setText("");
            fieldPostal.setText("");
            //            fieldGerente.setText("");
            //            fieldContacto1.setText("");
            //            fieldContacto2.setText("");
            resultListContactos = ObjectModelDAO.getResultQuery("FROM Contacto c order by c.idContacto asc");
            cb_gerente1.removeAllItems();
            cb_contacto1.removeAllItems();
            cb_contacto2.removeAllItems();

            for (Object object : resultListContactos) {
                Contacto c = (Contacto) object;
                cb_gerente1.addItem(c.getNombre());
                cb_contacto1.addItem(c.getNombre());
                cb_contacto2.addItem(c.getNombre());
            }

            String sql = "FROM Proveedor p order by p.idProveedor asc";
            resultListProveedores = ObjectModelDAO.getResultQuery(sql);
            JavaUtil.displayResult(resultListProveedores, tablaModfProveedor);
            tablaModfProveedor.setEditable(false);
            pos = -1;
            cb_gerente1.setSelectedIndex(pos);
            cb_contacto1.setSelectedIndex(pos);
            cb_contacto2.setSelectedIndex(pos);
        }

        if (panelScrudProveedor.getSelectedIndex() == 3) {
            String sql = "FROM Proveedor p order by p.idProveedor asc";
            resultListProveedores = ObjectModelDAO.getResultQuery(sql);

            JavaUtil.displayResult(resultListProveedores, tablaDeletProveedor);
            pos = -1;
            tablaDeletProveedor.setEditable(false);
        }
    }//GEN-LAST:event_panelScrudProveedorStateChanged

    private void TableModelData() {
        Vector<String> columnNames = new Vector<>();
        columnNames.add("NOMBRE");
        columnNames.add("TELEFONO 1");
        columnNames.add("FAX");
        columnNames.add("CORREO");
        columnNames.add("GERENTE");
        columnNames.add("CONTACTO");
        columnNames.add("FECHA DE CREACION");

        Vector<Object> data = new Vector<>();
        for (int i = 0; i < listadoProveedores.getRowCount(); i++) {
            Vector<Object> subdata = new Vector<>();

            for (int j = 0; j < listadoProveedores.getColumnCount(); j++) {
                if (columnNames.contains(listadoProveedores.getColumnName(j))) {
                    subdata.add(listadoProveedores.getValueAt(i, j));
                }
            }
            data.add(subdata);
        }
        tableModel = new DefaultTableModel(data, columnNames);
//        listadoProveedores.setModel(tableModel);
    }

    private void generarReporte() {
        try {
            JasperPrint jasperPrint = null;
            Map<String, Object> parametro = new HashMap<>();
            TableModelData();

            TableModelReport dataSourse = new TableModelReport(tableModel);

            parametro.put("REPORT_DATA_SOURSE", dataSourse);
            JasperReport reporte = (JasperReport) JRLoader.loadObject(this.getClass().getResourceAsStream(rutaJasper));
            jasperPrint = JasperFillManager.fillReport(reporte, null, dataSourse);
            JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);
            jasperViewer.setTitle("Reporte de Clasificación de Producto");
            jasperViewer.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error" + e);
        }
    }

    private void bt_GenerarReporteProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_GenerarReporteProveedoresActionPerformed
        generarReporte();
//        TableModelData();               

    }//GEN-LAST:event_bt_GenerarReporteProveedoresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCrearProveedor;
    private javax.swing.JButton bEliminarProveedor;
    private javax.swing.JButton bModfProve;
    private javax.swing.JButton bt_GenerarReporteProveedores;
    private javax.swing.JComboBox cb_contacto;
    private javax.swing.JComboBox cb_contacto1;
    private javax.swing.JComboBox cb_contacto2;
    private javax.swing.JComboBox cb_gerente;
    private javax.swing.JComboBox cb_gerente1;
    private javax.swing.JComboBox cb_otrocontacto;
    private javax.swing.JTextField fieldCorreo;
    private javax.swing.JTextField fieldCorreoProv;
    private javax.swing.JTextField fieldFax;
    private javax.swing.JTextField fieldFaxProv;
    private javax.swing.JTextField fieldNomb;
    private javax.swing.JTextField fieldNombProv;
    private javax.swing.JTextField fieldPostal;
    private javax.swing.JTextField fieldPostalProv;
    private javax.swing.JTextField fieldTlf1;
    private javax.swing.JTextField fieldTlf1Prov;
    private javax.swing.JTextField fieldTlf2;
    private javax.swing.JTextField fieldTlf2Prov;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private org.jdesktop.swingx.JXTable listadoProveedores;
    private javax.swing.JTabbedPane panelScrudProveedor;
    private org.jdesktop.swingx.JXTable tablaDeletProveedor;
    private org.jdesktop.swingx.JXTable tablaModfProveedor;
    // End of variables declaration//GEN-END:variables
}
