package gui.paneles;

import com.healthmarketscience.jackcess.ColumnBuilder;
import com.healthmarketscience.jackcess.Database;
import com.healthmarketscience.jackcess.DatabaseBuilder;
import com.healthmarketscience.jackcess.Table;
import com.healthmarketscience.jackcess.TableBuilder;
import hibernate.DAO.DaoQuery;
import util.JavaUtil;
import static util.JavaUtil.setTableCellAlignment;
import modelos.tablas.TableModelReport;
import hibernate.DAO.ObjectModelDAO;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import modelos.mapeos.SalidaParaTienda;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Types;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import modelos.mapeos.Almacen;
import modelos.mapeos.InventarioTienda;
import modelos.mapeos.InventarioTiendaPK;
import modelos.mapeos.Producto;
import modelos.mapeos.SalidaParaTiendaDetalle;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.hibernate.Query;

public class JPsalida_p_tienda extends javax.swing.JPanel {

    private List resultListProductoSalida;//detalle
    private List resultListPrecios;
    private boolean revisado = false;
    private int pos;
    private SalidaParaTienda cabecera = null;
    DefaultTableModel tableModel;
    private List resultListAlmacen;
    private List resultList_salidas;

    public final String rutaJasper = "/reportes/ReporteMercanciaAsignada.jasper";

    public JPsalida_p_tienda() {
        initComponents();

        setTableCellAlignment(JLabel.CENTER, listadoMercancia);

        //checkboxRevisado.setSelected(false);
        // setCB(buttonGrouptipo.isSelected(null));
        setCB_Tienda();

        listadoMercancia.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGrouptipo = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        panelCabezera = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cb_tienda1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        fieldfecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldPersonalDep = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fieldAyudante = new javax.swing.JTextField();
        cb_tienda2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cb_salidasregistradas = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        checkboxRevisado = new javax.swing.JCheckBox();
        jRadioButtonPendiente = new javax.swing.JRadioButton();
        jRadioButtonRevisado = new javax.swing.JRadioButton();
        panelFinal = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        fieldTotal = new javax.swing.JTextField();
        bGenerarReporte = new javax.swing.JButton();
        bImprimirEtiquetas = new javax.swing.JButton();
        panelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listadoMercancia = new org.jdesktop.swingx.JXTable();

        setToolTipText("");
        setMinimumSize(new java.awt.Dimension(5, 5));
        setPreferredSize(new java.awt.Dimension(5, 5));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        jPanel3.setLayout(new java.awt.BorderLayout());

        panelCabezera.setLayout(new javax.swing.BoxLayout(panelCabezera, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/tienda2 (2).png"))); // NOI18N
        jLabel1.setText("Tienda desde:");

        cb_tienda1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_tienda1ItemStateChanged(evt);
            }
        });
        cb_tienda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tienda1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_almacen/fecha.png"))); // NOI18N
        jLabel2.setText("Fecha:");

        fieldfecha.setEditable(false);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1418682263_Person_Undefined_Male_Light.png"))); // NOI18N
        jLabel4.setText("Facturadora:");

        fieldPersonalDep.setEditable(false);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1418682382_Person_Undefined_Female_Light.png"))); // NOI18N
        jLabel6.setText("Ayudante:");

        fieldAyudante.setEditable(false);

        cb_tienda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tienda2ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_almacen/1417636330_store.png"))); // NOI18N
        jLabel5.setText("Tienda hasta:");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_almacen/1417576112_Order_tracking.png"))); // NOI18N
        jLabel7.setText("Salidas Registradas:");

        cb_salidasregistradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_salidasregistradasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldPersonalDep)
                            .addComponent(fieldAyudante)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_tienda1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_tienda2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldfecha)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_salidasregistradas, 0, 577, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_tienda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_tienda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cb_salidasregistradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPersonalDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldAyudante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        panelCabezera.add(jPanel2);

        checkboxRevisado.setText("Revisado");
        checkboxRevisado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxRevisadoActionPerformed(evt);
            }
        });

        buttonGrouptipo.add(jRadioButtonPendiente);
        jRadioButtonPendiente.setSelected(true);
        jRadioButtonPendiente.setText("Pendiente");
        jRadioButtonPendiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPendienteActionPerformed(evt);
            }
        });

        buttonGrouptipo.add(jRadioButtonRevisado);
        jRadioButtonRevisado.setText("Revisado");
        jRadioButtonRevisado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRevisadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkboxRevisado)
                    .addComponent(jRadioButtonRevisado)
                    .addComponent(jRadioButtonPendiente))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jRadioButtonPendiente)
                .addGap(38, 38, 38)
                .addComponent(jRadioButtonRevisado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(checkboxRevisado)
                .addGap(44, 44, 44))
        );

        panelCabezera.add(jPanel1);

        jPanel3.add(panelCabezera, java.awt.BorderLayout.NORTH);

        jLabel10.setText("Total:");

        fieldTotal.setEditable(false);

        bGenerarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1415416322_list-accept.png"))); // NOI18N
        bGenerarReporte.setText("Generar Reporte");
        bGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGenerarReporteActionPerformed(evt);
            }
        });

        bImprimirEtiquetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/imprimir_bar-code.png"))); // NOI18N
        bImprimirEtiquetas.setText("Imprimir Etiquetas");
        bImprimirEtiquetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bImprimirEtiquetasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFinalLayout = new javax.swing.GroupLayout(panelFinal);
        panelFinal.setLayout(panelFinalLayout);
        panelFinalLayout.setHorizontalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinalLayout.createSequentialGroup()
                .addContainerGap(629, Short.MAX_VALUE)
                .addComponent(bImprimirEtiquetas)
                .addGap(40, 40, 40)
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bGenerarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelFinalLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelFinalLayout.setVerticalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFinalLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(fieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGenerarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bImprimirEtiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        jPanel3.add(panelFinal, java.awt.BorderLayout.SOUTH);

        listadoMercancia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "N°", "Codigo", "Referencia", "Descripción", "Cantidad", "Precio", "Descuento", "Bulto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listadoMercancia.setShowGrid(true);
        listadoMercancia.setSortable(false);
        jScrollPane1.setViewportView(listadoMercancia);

        javax.swing.GroupLayout panelTablaLayout = new javax.swing.GroupLayout(panelTabla);
        panelTabla.setLayout(panelTablaLayout);
        panelTablaLayout.setHorizontalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE)
        );
        panelTablaLayout.setVerticalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );

        jPanel3.add(panelTabla, java.awt.BorderLayout.CENTER);

        jScrollPane2.setViewportView(jPanel3);

        add(jScrollPane2);
    }// </editor-fold>//GEN-END:initComponents

    private void createMDB() throws IOException, SQLException {
        File archivo = new File("C:/Etiquetado Bulto Miyake/Etiquetas.mdb");
       //File archivo = new File("\\\\MIYAKE-FACTURA\\Etiquetado Bulto Miyake/Etiquetas.mdb3"); 
        ///Etiquetado Bulto Miyake/

        if (archivo.exists()) {
            archivo.delete();
        }

        archivo.createNewFile();
        Database db = DatabaseBuilder.create(Database.FileFormat.V2000, archivo);
        Table newTable = new TableBuilder("Tbl_Etiquetas")
                .addColumn(new ColumnBuilder("CodigoProducto")
                        .setSQLType(Types.NUMERIC))
                .addColumn(new ColumnBuilder("Referencia")
                        .setSQLType(Types.VARCHAR))
                .addColumn(new ColumnBuilder("DescripcionProducto")
                        .setSQLType(Types.VARCHAR))
                .addColumn(new ColumnBuilder("PrecioVenta")
                        .setSQLType(Types.FLOAT))
                .addColumn(new ColumnBuilder("CostoDolar")//siempre 0
                        .setSQLType(Types.NUMERIC))
                .addColumn(new ColumnBuilder("CodigoProveedor")
                        .setSQLType(Types.VARCHAR))
                .addColumn(new ColumnBuilder("Mes")
                        .setSQLType(Types.VARCHAR))
                .addColumn(new ColumnBuilder("Anno")
                        .setSQLType(Types.VARCHAR))
                .addColumn(new ColumnBuilder("TextoZona")//siempre vacio
                        .setSQLType(Types.VARCHAR))
                .addColumn(new ColumnBuilder("Cantidad")//siempre 1
                        .setSQLType(Types.NUMERIC))
                .addColumn(new ColumnBuilder("Adicional")//siempre vacio
                        .setSQLType(Types.VARCHAR))
                .addColumn(new ColumnBuilder("Marca")
                        .setSQLType(Types.VARCHAR))
                .addColumn(new ColumnBuilder("PrecioVentasi")
                        .setSQLType(Types.FLOAT))
                .toTable(db);

        Calendar now = Calendar.getInstance();

        for (Object rslDetalle : resultListProductoSalida) {
            //resultListProductoSalida es una lista de vectores de 3 indices
            //   en el primer indice esta el SalidaParaTiendaDetalle
            SalidaParaTiendaDetalle detalle = (SalidaParaTiendaDetalle) ((Object[]) rslDetalle)[0];
            String hql = "";

            hql = "FROM InventarioTienda ivt WHERE ivt.producto.idProducto = " + detalle.getProducto().getIdProducto()
                    + "AND ivt.almacen.idAlmacen=" + detalle.getSalidaParaTienda().getIdAlmacenHasta().getIdAlmacen();

//            hql = "FROM InventarioTiendaPK ivt WHERE ivt.idProducto.idProducto = " + detalle.getProducto().getIdProducto()
//                    + " AND ppt.idAlmacen.idAlmacen= " + detalle.getSalidaParaTienda().getIdAlmacenHasta().getIdAlmacen();
            List listadoProductosConPrecio = ObjectModelDAO.getResultQuery(hql);

            if (listadoProductosConPrecio.size() > 1) {
                JOptionPane.showMessageDialog(null, "Exiten dos precios distintos de un mismo producto en la tienda, \n No se cargará");
            } else {
                if (listadoProductosConPrecio.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "No existe producto en esta tienda, No se cargará");

                } else {
                    InventarioTienda ivt = (InventarioTienda) listadoProductosConPrecio.get(0);
                    Producto produc = ivt.getProducto();
                    Integer id = produc.getIdProducto();
                    String referencia = produc.getReferenciaProducto();
                    String descripcion = produc.getDescripcion();
                    Double precioCI = (ivt.getPrecioConDescuento() + (ivt.getPrecioConDescuento() * JavaUtil.iva));
                    Integer idproveedor = produc.getIdProveedor() == null ? null : produc.getIdProveedor().getIdProveedor();
                    String marca = produc.getIdMarca() == null ? "" : produc.getIdMarca().getNombre();
                    Float precioSI = ivt.getPrecioConDescuento();
                    for (int i = 0; i < detalle.getCantidadProducto(); i++) {

                        newTable.addRow(
                                id,
                                referencia,
                                descripcion,
                                precioCI,
                                0,
                                idproveedor + "",
                                now.get(Calendar.MONTH) + 1,
                                now.get(Calendar.YEAR),
                                "",
                                1,
                                "",
                                marca,
                                precioSI
                        );
                    }
                }
            }
        }
    }

    private void setCB(boolean tipo) {
        String hql = "FROM SalidaParaTienda s WHERE s.revisado = :revisado order by s.idSalida asc";
        DaoQuery q = ObjectModelDAO.createQueryDAO(hql);
        q.getQuery().setParameter("revisado", tipo);
        List resultList_sw = ObjectModelDAO.getResultQuery(q);

        cb_tienda1.removeAllItems();
        cb_tienda1.addItem("Todas");
        for (Object object : resultList_sw) {
            SalidaParaTienda c = (SalidaParaTienda) object;
            cb_tienda1.addItem(c.getIdSalida());
        }
    }

    private void setCB_Tienda() {
        resultListAlmacen = ObjectModelDAO.getResultQuery("FROM Almacen a order by a.idAlmacen asc");
        cb_tienda1.removeAllItems();
        cb_tienda1.addItem(JavaUtil.cons_seleccionar);
        cb_tienda1.addItem("Todas las Tiendas");
        cb_tienda2.removeAllItems();
        cb_tienda2.addItem(JavaUtil.cons_seleccionar);
        cb_tienda2.addItem("Todas las Tiendas");
        for (Object object : resultListAlmacen) {
            Almacen a = (Almacen) object;
            cb_tienda1.addItem(a.getNombre());
            cb_tienda2.addItem(a.getNombre());
        }
    }

    private void setCB_Salidas() {
        String tienda_pertenece_salida = "";
        String HQL;
        DaoQuery q = null;
        //T1 --- T2     TODAS CON TODAS, ES DECIR TODAS LAS SALIDAS
        if (cb_tienda1.getSelectedItem().equals("Todas las Tiendas")
                && cb_tienda2.getSelectedItem().equals("Todas las Tiendas")) {

            HQL = "FROM SalidaParaTienda s WHERE s.revisado = :revisado order by s.idSalida asc";

            q = ObjectModelDAO.createQueryDAO(HQL);
        }

        //T1 --- 2      TODAS CON ALGUNA EN ESPECIFICA
        if (cb_tienda1.getSelectedItem().equals("Todas las Tiendas")
                && cb_tienda2.getSelectedIndex() > 1) {//1 ES TODAS LAS TIENDAS

            HQL = "FROM SalidaParaTienda s WHERE s.idAlmacenHasta =:almchasta "
                    + " AND s.revisado = :revisado order by s.idSalida asc";

            q = ObjectModelDAO.createQueryDAO(HQL);
            q.getQuery().setParameter("almchasta", (Almacen) resultListAlmacen.get(cb_tienda2.getSelectedIndex() - 2));

            tienda_pertenece_salida = "Desde";
        }

        //2 --- T2      ALGUNA EN ESPECIFICA PARA TODAS
        if (cb_tienda1.getSelectedIndex() > 1//1 ES TODAS LAS TIENDAS
                && cb_tienda2.getSelectedItem().equals("Todas las Tiendas")) {

            HQL = "FROM SalidaParaTienda s WHERE s.idAlmacenDesde =:almcdesde "
                    + " AND s.revisado = :revisado order by s.idSalida asc";

            q = ObjectModelDAO.createQueryDAO(HQL);
            q.getQuery().setParameter("almcdesde", (Almacen) resultListAlmacen.get(cb_tienda1.getSelectedIndex() - 2));

            tienda_pertenece_salida = "Hasta";
        }

        //2 --- 3       ALGUNA EN ESPECIFICA PARA OTRA EN ESPECIFICA
        if (cb_tienda1.getSelectedIndex() > 1//1 ES TODAS LAS TIENDAS
                && cb_tienda2.getSelectedIndex() > 1) {//1 ES TODAS LAS TIENDAS

            HQL = "FROM SalidaParaTienda s WHERE s.idAlmacenHasta =:almchasta "
                    + "AND s.idAlmacenDesde =:almcdesde AND s.revisado = :revisado order by s.idSalida asc";

            q = ObjectModelDAO.createQueryDAO(HQL);
            q.getQuery().setParameter("almcdesde", (Almacen) resultListAlmacen.get(cb_tienda1.getSelectedIndex() - 2));
            q.getQuery().setParameter("almchasta", (Almacen) resultListAlmacen.get(cb_tienda2.getSelectedIndex() - 2));
        }

        q.getQuery().setParameter("revisado", jRadioButtonRevisado.isSelected());
        resultList_salidas = ObjectModelDAO.getResultQuery(q);

        cb_salidasregistradas.removeAllItems();
        // cb_salidasregistradas.addItem("Todas");
        if (resultList_salidas.isEmpty()) {
            cb_salidasregistradas.addItem("No tiene");
        }

        for (Object object : resultList_salidas) {
            SalidaParaTienda c = (SalidaParaTienda) object;
            if (tienda_pertenece_salida.equals("")) {
                cb_salidasregistradas.addItem(c.getIdSalida());
            } else {
                cb_salidasregistradas.addItem(c.getIdSalida() + (tienda_pertenece_salida.equals("Desde") ? " " + tienda_pertenece_salida + ": " + c.getIdAlmacenDesde().getNombre()
                        : " " + tienda_pertenece_salida + ": " + c.getIdAlmacenHasta().getNombre()));
            }
        }
    }

    private void cb_tienda1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_tienda1ItemStateChanged

//        if (evt.getStateChange() == ItemEvent.SELECTED) {
//
//            String sql = "";
//
//            cabecera = ObjectModelDAO.getObject((Integer) cb_Salidas.getSelectedItem(), SalidaParaTienda.class);
//            sql = "FROM SalidaParaTiendaDetalle s WHERE s.salidaParaTiendaDetallePK.idSalida = " 
//                    + cb_Salidas.getSelectedItem();
//            resultListProductoSalida = ObjectModelDAO.getResultQuery(sql);
//
//            if (resultListProductoSalida.isEmpty()) {
//                return;
//            }
//
//            if (cabecera.getIdSalida() != null) {
//                fieldnumFact.setText(cabecera.getIdSalida().toString());
//            } else {
//                fieldnumFact.setText("");
//            }
//            if (cabecera.getIdAlmacenHasta() != null) {
//                fieldTienda.setText(cabecera.getIdAlmacenHasta().getDescripcion());
//            } else {
//                fieldTienda.setText("");
//            }
//            if (cabecera.getIdUsuario1() != null) {
//                fieldPersonalDep.setText(cabecera.getIdUsuario1().getNombre());
//            } else {
//                fieldPersonalDep.setText("");
//            }
//            if (cabecera.getIdUsuario2() != null) {
//                fieldAyudante.setText(cabecera.getIdUsuario2().getNombre());
//            } else {
//                fieldAyudante.setText("");
//            }
//            if (cabecera.getTotal() != null) {
//                fieldTotal.setText(cabecera.getTotal() + "");
//            } else {
//                fieldTotal.setText("");
//            }
//
//            JavaUtil.displayResult(resultListProductoSalida, listadoMercancia);
//            listadoMercancia.setEditable(false);
//            checkboxRevisado.setSelected(false);
//            pos = cb_Salidas.getSelectedIndex();
//        }
    }//GEN-LAST:event_cb_tienda1ItemStateChanged

    //Para probar el reporte con multiples datos y de bastante longitud
    private void TableModelData() {
        Vector<String> columnNames = new Vector<>();
        columnNames.add("Codigo");
        columnNames.add("Referencia");
        columnNames.add("Descripcion");
        columnNames.add("Cantidad");
        columnNames.add("Precio");
        columnNames.add("Bulto");

        Vector<Object> data = new Vector<>();
        for (int i = 0; i < 100; i++) {
            Vector<Object> subdata = new Vector<>();
            for (int j = 0; j < 500; j++) {
                if (j == 2) {
                    subdata.add("fgdretttttetrrrrrrrrrrrrrrrrrrerererererererererererererertygfhfd");
                } else {
                    if (j == 4) {
                        subdata.add((float) i * 400);
                    } else {
                        subdata.add(i * 850);
                    }
                }

            }
            data.add(subdata);
        }

        tableModel = new DefaultTableModel(data, columnNames);
    }

    private void generarReporte() {
        try {
            JasperPrint jasperPrint = null;
            TableModelData();
            Map<String, Object> parametro = new HashMap<>();
//            String s = "";
//
//            for (int i = 0; i < tableModel.getColumnCount(); i++) {
//                s += tableModel.getColumnName(i) + "\t" + Integer.valueOf(i) + "\n";
//            }
            TableModelReport dataSourse = new TableModelReport(listadoMercancia.getModel());

            parametro.put("Fecha", fieldfecha.getText());
            parametro.put("Tienda", cb_tienda1.getSelectedItem().equals("Todas las Tiendas") ? "" : cb_tienda1.getSelectedItem().toString());
            parametro.put("Tienda2", cb_tienda2.getSelectedItem().toString());
            parametro.put("Facturadora", fieldPersonalDep.getText());
            parametro.put("Ayudante", fieldAyudante.getText());
            parametro.put("Salida", cb_salidasregistradas.getSelectedItem().toString());
            parametro.put("REPORT_DATA_SOURSE", dataSourse);
            JasperReport reporte = (JasperReport) JRLoader.loadObject(this.getClass().getResourceAsStream(rutaJasper));
            jasperPrint = JasperFillManager.fillReport(reporte, parametro, dataSourse);
            JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);
            jasperViewer.setTitle("Reporte de Salida de Mercancía");
            jasperViewer.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error" + e);
        }
    }

    private void cb_tienda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tienda1ActionPerformed

        if (cb_tienda1.getSelectedIndex() == -1 || cb_tienda2.getSelectedIndex() == -1) {
            return;
        }

        if (cb_tienda1.getSelectedItem().equals(JavaUtil.cons_seleccionar)
                || cb_tienda2.getSelectedItem().equals(JavaUtil.cons_seleccionar)) {
            cb_salidasregistradas.removeAllItems();
            resultListProductoSalida = null;
            cabecera = null;
            fieldfecha.setText("");
            fieldPersonalDep.setText("");
            fieldAyudante.setText("");
            fieldTotal.setText("");
            pos = -1;
            listadoMercancia.setModel(new DefaultTableModel());
            return;
        }
        setCB_Salidas();
    }//GEN-LAST:event_cb_tienda1ActionPerformed

    private void bGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGenerarReporteActionPerformed
        if (checkboxRevisado.isSelected()) {

//            if (JOptionPane.showConfirmDialog(this, "¿Esta Seguro que desea marcar como revisado este Formulario de Mercancía Asignada a Tienda?", "Información", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
//                cabecera.setRevisado(true);
            if (jRadioButtonPendiente.isSelected()) {
                ObjectModelDAO.updateObject(cabecera);
            }
            // cb_Salidas.removeItemAt (cb_Salidas.getSelectedIndex());
            // sw = true;
            // pos = cb_Salidas.getSelectedIndex();
            generarReporte();
            //    setCB();

        }

//        } else {
//            JOptionPane.showMessageDialog(this, "Deben Marcar que ha revisado este Formulario de Mercancía Asignada a Tienda");
//        }
    }//GEN-LAST:event_bGenerarReporteActionPerformed

    private void bImprimirEtiquetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bImprimirEtiquetasActionPerformed
        if (checkboxRevisado.isSelected()) {
            String filePath = "C:/Etiquetado Bulto Miyake/Imprime.bat";
            //String filePath = "\\\\MIYAKE-FACTURA\\Etiquetado Bulto Miyake/Imprime.bat";
            try {
                createMDB();
                Process p = Runtime.getRuntime().exec(filePath);
                JOptionPane.showMessageDialog(this, "Se han generado las etiquetas..");
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Deben Marcar que ha revisado este Formulario de Mercancía Asignada a Tienda");
        }
    }//GEN-LAST:event_bImprimirEtiquetasActionPerformed

    private void checkboxRevisadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxRevisadoActionPerformed
        if (cb_tienda1.getSelectedIndex() == -1 || cb_tienda1.getSelectedItem().equals("Seleccionar")) {
            JOptionPane.showMessageDialog(this, "Seleccione un Formulario de Mercancía Asignada");
            checkboxRevisado.setSelected(false);
            return;
        } else {
            if (checkboxRevisado.isSelected() && JOptionPane.showConfirmDialog(this,
                    "¿Esta Seguro que desea marcar como revisado este Formulario de Mercancía Asignada a Tienda?",
                    "Información", JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION) {
                checkboxRevisado.setSelected(false);
            }
            cabecera.setRevisado(checkboxRevisado.isSelected());
            // System.out.println(cabecera.getRevisado());
        }
    }//GEN-LAST:event_checkboxRevisadoActionPerformed
    public static void clearTable(final JTable table) {
        for (int i = 0; i < table.getRowCount(); i++) {
            for (int j = 0; j < table.getColumnCount(); j++) {
                table.setValueAt("", i, j);
            }
        }
    }

    private void jRadioButtonPendienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPendienteActionPerformed

        setCB_Salidas();
        checkboxRevisado.setSelected(false);
        checkboxRevisado.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonPendienteActionPerformed

    private void jRadioButtonRevisadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRevisadoActionPerformed

        setCB_Salidas();
        checkboxRevisado.setSelected(true);
        checkboxRevisado.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonRevisadoActionPerformed

    private void cb_tienda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tienda2ActionPerformed

        if (cb_tienda1.getSelectedIndex() == -1 || cb_tienda2.getSelectedIndex() == -1) {
            return;
        }

        if (cb_tienda1.getSelectedItem().equals(JavaUtil.cons_seleccionar)
                || cb_tienda2.getSelectedItem().equals(JavaUtil.cons_seleccionar)) {
            cb_salidasregistradas.removeAllItems();
            resultListProductoSalida = null;
            cabecera = null;
            fieldfecha.setText("");
            fieldPersonalDep.setText("");
            fieldAyudante.setText("");
            fieldTotal.setText("");
            pos = -1;
            listadoMercancia.setModel(new DefaultTableModel());
            return;
        }

        setCB_Salidas();
    }//GEN-LAST:event_cb_tienda2ActionPerformed


    private void cb_salidasregistradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_salidasregistradasActionPerformed
        if (cb_salidasregistradas.getSelectedIndex() == -1 || cb_salidasregistradas.getSelectedItem().equals("No tiene")) {
            listadoMercancia.setModel(new DefaultTableModel());
            fieldfecha.setText("");
            fieldPersonalDep.setText("");
            fieldAyudante.setText("");
            return;
        }
        SalidaParaTienda salida = (SalidaParaTienda) resultList_salidas.get(cb_salidasregistradas.getSelectedIndex());
        String HQL = "SELECT s,ivt.precioConDescuento,ivt.descuento"
                + " FROM SalidaParaTiendaDetalle s,InventarioTienda ivt "
                + " INNER JOIN s.salidaParaTienda spt WHERE spt.idSalida= " + salida.getIdSalida()
                + " AND ivt.producto=s.producto"
                // + " AND spt.revisado = " + tipo
                + " ORDER BY s.nroRenglon ASC";
//                "SELECT s,ppt.precio,ppt.descuento"
//                + " FROM SalidaParaTiendaDetalle s,PrecioProductoTienda ppt INNER JOIN  s.salidaParaTienda spt"
//                + " WHERE spt.idSalida =" + cb_Salidas.getSelectedItem()
//                + " AND ppt.idProducto=s.producto AND ppt.idAlmacen=spt.idAlmacenHasta";

//        cabecera = ObjectModelDAO.getObject((Integer) cb_Salidas.getSelectedItem(), SalidaParaTienda.class);
//        sql = "FROM SalidaParaTiendaDetalle s WHERE s.salidaParaTiendaDetallePK.idSalida ="
//                + cb_Salidas.getSelectedItem();
//        System.out.println(sql);
        resultListProductoSalida = ObjectModelDAO.getResultQuery(HQL);

        if (resultListProductoSalida.isEmpty()) {
            listadoMercancia.setModel(new DefaultTableModel());
            return;
        }

        cabecera = ((SalidaParaTiendaDetalle) ((Object[]) resultListProductoSalida.get(0))[0]).getSalidaParaTienda();

        //SalidaParaTienda cabecera = ((SalidaParaTiendaDetalle) resultListProductoSalida.get(0)).getSalidaParaTienda();
        if (cabecera.getFechaAsignacion() != null) {
            SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("dd-MM-yyyy");
            fieldfecha.setText(DATE_FORMAT.format(cabecera.getFechaAsignacion()));
        } else {
            fieldfecha.setText("");
        }
        if (cabecera.getIdUsuario1() != null) {
            fieldPersonalDep.setText(cabecera.getIdUsuario1().getNombre());
        } else {
            fieldPersonalDep.setText("");
        }
        if (cabecera.getIdUsuario2() != null) {
            fieldAyudante.setText(cabecera.getIdUsuario2().getNombre());
        } else {
            fieldAyudante.setText("");
        }
        if (cabecera.getTotal() != null) {
            fieldTotal.setText(cabecera.getTotal() + "");
        } else {
            fieldTotal.setText("");
        }

        JavaUtil.displayResult(resultListProductoSalida, listadoMercancia);
        listadoMercancia.setEditable(false);
        pos = cb_salidasregistradas.getSelectedIndex();
    }//GEN-LAST:event_cb_salidasregistradasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bGenerarReporte;
    private javax.swing.JButton bImprimirEtiquetas;
    private javax.swing.ButtonGroup buttonGrouptipo;
    private javax.swing.JComboBox cb_salidasregistradas;
    private javax.swing.JComboBox cb_tienda1;
    private javax.swing.JComboBox cb_tienda2;
    private javax.swing.JCheckBox checkboxRevisado;
    private javax.swing.JTextField fieldAyudante;
    private javax.swing.JTextField fieldPersonalDep;
    private javax.swing.JTextField fieldTotal;
    private javax.swing.JTextField fieldfecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonPendiente;
    private javax.swing.JRadioButton jRadioButtonRevisado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXTable listadoMercancia;
    private javax.swing.JPanel panelCabezera;
    private javax.swing.JPanel panelFinal;
    private javax.swing.JPanel panelTabla;
    // End of variables declaration//GEN-END:variables
}
