/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.paneles;

import util.JavaUtil;
import static util.JavaUtil.setTableCellAlignment;
import hibernate.DAO.ObjectModelDAO;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import modelos.mapeos.Ubicacion;

public class JPubicacion extends javax.swing.JPanel {

    private List resultList;
    private int pos;
    private Integer tabCrud;

    public JPubicacion(Integer tabCrud) {
        this.tabCrud = tabCrud;
        initComponents();

        setTableCellAlignment(JLabel.CENTER, tablaConsultaUbicacion);
        setTableCellAlignment(JLabel.CENTER, tablaModificarUbicacion);
        setTableCellAlignment(JLabel.CENTER, tablaEliminarUbicacion);
        tablaConsultaUbicacion.getTableHeader().setReorderingAllowed(false);
        tablaConsultaUbicacion.getTableHeader().setReorderingAllowed(false);
        tablaConsultaUbicacion.getTableHeader().setReorderingAllowed(false);

        tablaModificarUbicacion.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent lse) {
                if (!lse.getValueIsAdjusting()) {

                    pos = tablaModificarUbicacion.getSelectedRow();
                    if (pos == -1) {
                        return;
                    }
                    Ubicacion u = (Ubicacion) resultList.get(pos);
                    lb_numero.setText(u.getIdUbicacion().toString());
                    tf_pais1.setText(u.getPais());
                    tf_ciudad1.setText(u.getCiudad());
                    tf_direccion3.setText(u.getDireccion());
                }
            }
        });

        tablaEliminarUbicacion.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent lse) {
                if (!lse.getValueIsAdjusting()) {

                    if (tablaEliminarUbicacion.getSelectedRow() == -1) {
                        return;
                    }
                    pos = tablaEliminarUbicacion.getSelectedRow();

                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelScrudUbic = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaConsultaUbicacion = new org.jdesktop.swingx.JXTable();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tf_pais = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_ciudad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_direccion1 = new javax.swing.JTextField();
        crear = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaCrearUbicacion = new org.jdesktop.swingx.JXTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaModificarUbicacion = new org.jdesktop.swingx.JXTable();
        jPanel5 = new javax.swing.JPanel();
        modificar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lb_numero = new javax.swing.JLabel();
        tf_direccion3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_pais1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_ciudad1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaEliminarUbicacion = new org.jdesktop.swingx.JXTable();
        eliminar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(5, 5));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        panelScrudUbic.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                panelScrudUbicStateChanged(evt);
            }
        });

        jPanel2.setPreferredSize(new java.awt.Dimension(5, 5));

        tablaConsultaUbicacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID UBICACION", "PAIS", "CIUDAD", "DIRECCION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaConsultaUbicacion.setHorizontalScrollEnabled(true);
        tablaConsultaUbicacion.setSortable(false);
        jScrollPane1.setViewportView(tablaConsultaUbicacion);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1416622346_xmag.png"))); // NOI18N
        jLabel15.setText("Para realizar Busqueda: Haga Click en la tabla + CTRL F");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
        );

        panelScrudUbic.addTab("Consultar", jPanel2);

        jPanel1.setPreferredSize(new java.awt.Dimension(5, 5));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/World-024.png"))); // NOI18N
        jLabel3.setText("Pais");

        tf_pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_paisActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/companies.png"))); // NOI18N
        jLabel6.setText("Ciudad");

        tf_ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ciudadActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1418871427_map-24.png"))); // NOI18N
        jLabel7.setText("Dirección");

        tf_direccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_direccion1ActionPerformed(evt);
            }
        });

        crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/crearUbicacion.png"))); // NOI18N
        crear.setText("Crear Ubicación");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crear)
                    .addComponent(tf_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_pais, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_direccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(tf_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(tf_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(tf_direccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(crear)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.WEST);

        tablaCrearUbicacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID UBICACION", "PAIS", "CIUDAD", "DIRECCION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablaCrearUbicacion);

        jPanel1.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        panelScrudUbic.addTab("Crear", jPanel1);

        jPanel3.setPreferredSize(new java.awt.Dimension(5, 5));
        jPanel3.setLayout(new java.awt.BorderLayout());

        tablaModificarUbicacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID UBICACION", "PAIS", "CIUDAD", "DIRECCION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaModificarUbicacion.setHorizontalScrollEnabled(true);
        tablaModificarUbicacion.setSortable(false);
        jScrollPane2.setViewportView(tablaModificarUbicacion);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1415416498_Circulation.png"))); // NOI18N
        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        jLabel5.setText("Número:");

        lb_numero.setText("numero");

        tf_direccion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_direccion3ActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/World-024.png"))); // NOI18N
        jLabel10.setText("Pais");

        tf_pais1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pais1ActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/companies.png"))); // NOI18N
        jLabel11.setText("Ciudad");

        tf_ciudad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ciudad1ActionPerformed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1418871427_map-24.png"))); // NOI18N
        jLabel12.setText("Dirección");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_pais1)
                    .addComponent(tf_ciudad1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modificar)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_numero))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tf_direccion3))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lb_numero))
                .addGap(21, 21, 21)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_pais1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel11)
                .addGap(21, 21, 21)
                .addComponent(tf_ciudad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(tf_direccion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, java.awt.BorderLayout.EAST);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1416622346_xmag.png"))); // NOI18N
        jLabel16.setText("Para realizar Busqueda: Haga Click en la tabla + CTRL F");
        jPanel3.add(jLabel16, java.awt.BorderLayout.PAGE_START);

        panelScrudUbic.addTab("Modificar", jPanel3);

        jPanel4.setPreferredSize(new java.awt.Dimension(5, 5));

        tablaEliminarUbicacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID UBICACION", "PAIS", "CIUDAD", "DIRECCION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEliminarUbicacion.setSortable(false);
        jScrollPane3.setViewportView(tablaEliminarUbicacion);

        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1415657185_remove-sign-32.png"))); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1416622346_xmag.png"))); // NOI18N
        jLabel17.setText("Para realizar Busqueda: Haga Click en la tabla + CTRL F");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminar)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        panelScrudUbic.addTab("Eliminar", jPanel4);

        panelScrudUbic.setSelectedIndex(-1);

        add(panelScrudUbic);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_paisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_paisActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        if (!tf_pais.getText().equals("")) {

            if (JOptionPane.showConfirmDialog(this, "¿Está seguro de crear la"
                    + " nueva ubicación ?",
                    "Información", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                ObjectModelDAO.saveObject(new Ubicacion(
                        tf_pais.getText(),
                        tf_ciudad.getText(),
                        tf_direccion1.getText()
                ));

                String sql = "FROM Ubicacion u order by u.idUbicacion asc";
                resultList = ObjectModelDAO.getResultQuery(sql);
                JavaUtil.displayResult(resultList, tablaCrearUbicacion);
                tablaModificarUbicacion.setEditable(false);
                tablaModificarUbicacion.setRowSelectionInterval(resultList.size()-1, resultList.size()-1);
            }
        }
    }//GEN-LAST:event_crearActionPerformed

    private void tf_ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ciudadActionPerformed

    private void tf_direccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_direccion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_direccion1ActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        if (pos == -1 || tf_pais1.getText().equals("")) {
            return;
        }

        if (JOptionPane.showConfirmDialog(this, "¿Está seguro de modificar la"
                + " ubicación ?",
                "Información", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

            try {
                int pos = this.pos;
                Ubicacion u = (Ubicacion) resultList.get(pos);
                u.setPais(tf_pais1.getText());
                u.setCiudad(tf_ciudad1.getText());
                u.setDireccion(tf_direccion3.getText());
                ObjectModelDAO.updateObject(u);

                String sql = "FROM Ubicacion u order by u.idUbicacion asc";
                resultList = ObjectModelDAO.getResultQuery(sql);
                JavaUtil.displayResult(resultList, tablaModificarUbicacion);
                tablaModificarUbicacion.setEditable(false);
                tablaModificarUbicacion.setRowSelectionInterval(pos, pos);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(
                        null,
                        "Mensaje:\n\t" + e.getMessage(),
                        "Error Update",
                        JOptionPane.ERROR_MESSAGE
                );
                Logger.getLogger(JPubicacion.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void tf_direccion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_direccion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_direccion3ActionPerformed

    private void tf_pais1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pais1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_pais1ActionPerformed

    private void tf_ciudad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ciudad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ciudad1ActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        if (pos == -1) {
            return;
        }

        if (JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar la"
                + " ubicación ?", "Información", JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION) {

            ObjectModelDAO.deleteObject(resultList.get(pos));
            String sql = "FROM Ubicacion u order by u.idUbicacion asc";
            resultList = ObjectModelDAO.getResultQuery(sql);
            JavaUtil.displayResult(resultList, tablaEliminarUbicacion);
            pos = -1;
            tablaEliminarUbicacion.setEditable(false);
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void panelScrudUbicStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_panelScrudUbicStateChanged

        if (panelScrudUbic.getTabCount() != 4) {
            return;
        }

        //verifica si debe abrir un panel desde la llamada
        if (this.tabCrud != null) {
            int tabCrud = this.tabCrud.intValue();
            this.tabCrud = null;
            panelScrudUbic.setSelectedIndex(tabCrud);
            return;
        }

        if (panelScrudUbic.getSelectedIndex() == 0) {
            String sql = "FROM Ubicacion u order by u.idUbicacion asc";
            resultList = ObjectModelDAO.getResultQuery(sql);

            JavaUtil.displayResult(resultList, tablaConsultaUbicacion);
            tablaConsultaUbicacion.setEditable(false);
        }

        if (panelScrudUbic.getSelectedIndex() == 1) {
            tf_pais.setText("");
            tf_ciudad.setText("");
            tf_direccion1.setText("");
            String sql = "FROM Ubicacion u order by u.idUbicacion asc";
            resultList = ObjectModelDAO.getResultQuery(sql);
            JavaUtil.displayResult(resultList, tablaCrearUbicacion);
        }

        if (panelScrudUbic.getSelectedIndex() == 2) {
            lb_numero.setText("");
            tf_pais1.setText("");
            tf_ciudad1.setText("");
            tf_direccion3.setText("");
            String sql = "FROM Ubicacion u order by u.idUbicacion asc";
            resultList = ObjectModelDAO.getResultQuery(sql);
            JavaUtil.displayResult(resultList, tablaModificarUbicacion);
            pos = -1;
            tablaModificarUbicacion.setEditable(false);

        }

        if (panelScrudUbic.getSelectedIndex() == 3) {
            String sql = "FROM Ubicacion u order by u.idUbicacion asc";
            resultList = ObjectModelDAO.getResultQuery(sql);

            JavaUtil.displayResult(resultList, tablaEliminarUbicacion);
            pos = -1;
            tablaEliminarUbicacion.setEditable(false);
        }
    }//GEN-LAST:event_panelScrudUbicStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crear;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lb_numero;
    private javax.swing.JButton modificar;
    private javax.swing.JTabbedPane panelScrudUbic;
    private org.jdesktop.swingx.JXTable tablaConsultaUbicacion;
    private org.jdesktop.swingx.JXTable tablaCrearUbicacion;
    private org.jdesktop.swingx.JXTable tablaEliminarUbicacion;
    private org.jdesktop.swingx.JXTable tablaModificarUbicacion;
    private javax.swing.JTextField tf_ciudad;
    private javax.swing.JTextField tf_ciudad1;
    private javax.swing.JTextField tf_direccion1;
    private javax.swing.JTextField tf_direccion3;
    private javax.swing.JTextField tf_pais;
    private javax.swing.JTextField tf_pais1;
    // End of variables declaration//GEN-END:variables
}
