package gui;

import hibernate.anotaciones.util.JavaUtil;
import hibernate.anotaciones.util.ObjectModelDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import modelos.Clasificacion;
import modelos.Departamento;


public class Fclasificacion extends javax.swing.JFrame {


    private List resultList_clasificacion;
    private List resultList_departamento;
    private int pos;

    public Fclasificacion() {
        initComponents();

        tablaDeletClasif.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent lse) {
                if (!lse.getValueIsAdjusting()) {

                    if (tablaDeletClasif.getSelectedRow() == -1) {
                        return;
                    }
                    pos = tablaDeletClasif.getSelectedRow();

                }
            }
        });

        tablaModfClasif.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent lse) {
                if (!lse.getValueIsAdjusting()) {

                    if (tablaModfClasif.getSelectedRow() == -1) {
                        return;
                    }
                    pos = tablaModfClasif.getSelectedRow();
                    Clasificacion c = (Clasificacion) resultList_clasificacion.get(pos);
                    modfNombre.setText(c.getNombre());
                    idClasificacion.setText(c.getIdClasificacion().toString());
                    cb_clasificacionModificar.setSelectedItem(c.getIdDepartamento().getNombre());
                }
            }
        ;
    }

    );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevClasf1 = new javax.swing.JTextField();
        cb_dep1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelScrudClasif = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listadoClasif = new org.jdesktop.swingx.JXTable();
        jPanel2 = new javax.swing.JPanel();
        nuevClasf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bCrear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cb_dep = new javax.swing.JComboBox();
        b_CrearDept = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaModfClasif = new org.jdesktop.swingx.JXTable();
        modfNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cb_clasificacionModificar = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        idClasificacion = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        b_CrearDept1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        bDeletClasif = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaDeletClasif = new org.jdesktop.swingx.JXTable();

        cb_dep1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Nombre Clasificación");

        jLabel4.setText("Nombre Departamento");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelScrudClasif.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                panelScrudClasifStateChanged(evt);
            }
        });

        listadoClasif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Clasificación", "Nombre Clasificación", "Departamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(listadoClasif);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );

        panelScrudClasif.addTab("Consultar", jPanel1);

        jLabel1.setText("Nombre Clasificación:");

        bCrear.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\Imagenes Interfaz\\button-add-icon.png")); // NOI18N
        bCrear.setText("Crear Clasificación");
        bCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre Departamento");

        b_CrearDept.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\Imagenes Interfaz\\button-33add-icon.png")); // NOI18N
        b_CrearDept.setText("Crear Departamento");
        b_CrearDept.setMargin(new java.awt.Insets(2, 8, 2, 8));
        b_CrearDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_CrearDeptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nuevClasf)
                    .addComponent(cb_dep, 0, 193, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(b_CrearDept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bCrear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nuevClasf))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_dep)
                    .addComponent(b_CrearDept, javax.swing.GroupLayout.PREFERRED_SIZE, 32, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(bCrear)
                .addContainerGap(227, Short.MAX_VALUE))
        );

        panelScrudClasif.addTab("Crear", jPanel2);

        tablaModfClasif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Clasificación", "Nombre", "Departamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablaModfClasif);

        jLabel5.setText("Nombre Clasificación");

        jLabel6.setText("Nombre Departamento");

        jLabel7.setText("ID Clasificacion");

        idClasificacion.setText("ID Clasificacion");

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\Imagenes Interfaz\\guardar.png")); // NOI18N
        jButton1.setText("Modificar Clasificación");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        b_CrearDept1.setText("Crear Departamento");
        b_CrearDept1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_CrearDept1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cb_clasificacionModificar, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(idClasificacion))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modfNombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_CrearDept1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(idClasificacion))
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addGap(11, 11, 11)
                .addComponent(modfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_clasificacionModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b_CrearDept1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelScrudClasif.addTab("Modificar", jPanel3);

        bDeletClasif.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\Imagenes Interfaz\\borrar5.png")); // NOI18N
        bDeletClasif.setText("Eliminar");
        bDeletClasif.setMargin(new java.awt.Insets(2, 6, 2, 14));
        bDeletClasif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeletClasifActionPerformed(evt);
            }
        });

        tablaDeletClasif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Clasificación", "Nombre", "Departamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaDeletClasif);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bDeletClasif, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(bDeletClasif)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelScrudClasif.addTab("Eliminar", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelScrudClasif, javax.swing.GroupLayout.PREFERRED_SIZE, 504, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelScrudClasif)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelScrudClasifStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_panelScrudClasifStateChanged
        if (panelScrudClasif.getSelectedIndex() == 0) {
            String sql = "FROM Clasificacion c order by c.idClasificacion asc";
            List resultList = ObjectModelDAO.getResultQuery(sql);

            JavaUtil.displayResult(resultList, listadoClasif);
            listadoClasif.setEditable(false);
        }
        if (panelScrudClasif.getSelectedIndex() == 1) {
            nuevClasf.setText("");
            resultList_clasificacion = ObjectModelDAO.getResultQuery("FROM Departamento d order by d.idDepartamento asc");
            cb_dep.removeAllItems();
            for (Object object : resultList_clasificacion) {
                Departamento d = (Departamento) object;
                cb_dep.addItem(d.getNombre());
            }

        }
        if (panelScrudClasif.getSelectedIndex() == 2) {
            idClasificacion.setText("");
            modfNombre.setText("");
            resultList_departamento = ObjectModelDAO.getResultQuery("FROM Departamento d order by d.idDepartamento asc");
            cb_clasificacionModificar.removeAllItems();
            for (Object object : resultList_departamento) {
                Departamento d = (Departamento) object;
                cb_clasificacionModificar.addItem(d.getNombre());
            }
            String sql = "FROM Clasificacion c order by c.idClasificacion asc";
            resultList_clasificacion = ObjectModelDAO.getResultQuery(sql);
            JavaUtil.displayResult(resultList_clasificacion, tablaModfClasif);
            tablaModfClasif.setEditable(false);
            pos = -1;
            cb_clasificacionModificar.setSelectedIndex(pos);

        }

        if (panelScrudClasif.getSelectedIndex() == 3) {
            String sql = "FROM Clasificacion c order by c.idClasificacion asc";
            resultList_clasificacion = ObjectModelDAO.getResultQuery(sql);

            JavaUtil.displayResult(resultList_clasificacion, tablaDeletClasif);
            pos = -1;
            tablaDeletClasif.setEditable(false);
        }
    }//GEN-LAST:event_panelScrudClasifStateChanged

    private void bCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearActionPerformed
        if (!nuevClasf.getText().equals("")) {
            if (JOptionPane.showConfirmDialog(rootPane, "¿Está seguro de crear "
                    + " una nueva clasificacion : " + nuevClasf.getText() + "?",
                    "Información", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                ObjectModelDAO.saveObject(new Clasificacion(
                        nuevClasf.getText(),
                        (Departamento) resultList_clasificacion.get(cb_dep.getSelectedIndex()))
                );

            }
        }
    }//GEN-LAST:event_bCrearActionPerformed

    private void bDeletClasifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeletClasifActionPerformed
        if (pos == -1) {
            return;
        }

        String valor = tablaDeletClasif.getValueAt(tablaDeletClasif.getSelectedRow(), tablaDeletClasif.getSelectedColumn()).toString();
        if (JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar la"
                + " Clasificación " + valor + "?", "Información", JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION) {

            ObjectModelDAO.deleteObject(resultList_clasificacion.get(pos));
            String sql = "FROM Clasificacion c order by c.idClasificacion asc";
            resultList_clasificacion = ObjectModelDAO.getResultQuery(sql);
            JavaUtil.displayResult(resultList_clasificacion, tablaDeletClasif);
            pos = -1;
            tablaDeletClasif.setEditable(false);
        }
    }//GEN-LAST:event_bDeletClasifActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (pos == -1 || modfNombre.getText().equals("")) {
            return;
        }

        String valor = tablaModfClasif.getValueAt(tablaModfClasif.getSelectedRow(), 1).toString();//1 por el nombre
        if (JOptionPane.showConfirmDialog(null, "¿Está seguro de modificar el"
                + " Departamento " + valor + "?", "Información", JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION) {

            int posOr = this.pos;
            Clasificacion c = (Clasificacion) resultList_clasificacion.get(posOr);
            c.setNombre(modfNombre.getText());
            c.setIdDepartamento((Departamento) resultList_departamento.get(cb_clasificacionModificar.getSelectedIndex()));
            ObjectModelDAO.updateObject(c);

            resultList_departamento = ObjectModelDAO.getResultQuery("FROM Departamento d order by d.idDepartamento asc");
            cb_clasificacionModificar.removeAllItems();
            for (Object object : resultList_departamento) {
                Departamento d = (Departamento) object;
                cb_clasificacionModificar.addItem(d.getNombre());
            }
            String sql = "FROM Clasificacion c order by c.idClasificacion asc";
            resultList_clasificacion = ObjectModelDAO.getResultQuery(sql);
            JavaUtil.displayResult(resultList_clasificacion, tablaModfClasif);
            tablaModfClasif.setEditable(false);
            tablaModfClasif.setRowSelectionInterval(posOr, posOr);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b_CrearDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_CrearDeptActionPerformed
        new Fdepartamento().setVisible(true);
    }//GEN-LAST:event_b_CrearDeptActionPerformed

    private void b_CrearDept1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_CrearDept1ActionPerformed
        new Fdepartamento().setVisible(true);
    }//GEN-LAST:event_b_CrearDept1ActionPerformed

    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fclasificacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCrear;
    private javax.swing.JButton bDeletClasif;
    private javax.swing.JButton b_CrearDept;
    private javax.swing.JButton b_CrearDept1;
    private javax.swing.JComboBox cb_clasificacionModificar;
    private javax.swing.JComboBox cb_dep;
    private javax.swing.JComboBox cb_dep1;
    private javax.swing.JLabel idClasificacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private org.jdesktop.swingx.JXTable listadoClasif;
    private javax.swing.JTextField modfNombre;
    private javax.swing.JTextField nuevClasf;
    private javax.swing.JTextField nuevClasf1;
    private javax.swing.JTabbedPane panelScrudClasif;
    private org.jdesktop.swingx.JXTable tablaDeletClasif;
    private org.jdesktop.swingx.JXTable tablaModfClasif;
    // End of variables declaration//GEN-END:variables
}
